import { app, BrowserWindow, clipboard, dialog, ipcMain, Menu, nativeImage, Notification, screen, session, Tray, shell } from "electron";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import QRCode from "qrcode";
import {
  activeDaemonPort,
  daemonPortReason,
  fetchDaemonHealth,
  getPairUrl,
  isDaemonDown,
  readApiToken,
  readDaemonState,
  reconnectState,
  restartDaemon,
  sidecarExitInfo,
  setSidecarRelayUrl,
  startDaemonSidecar,
  stateFilePath,
  stopDaemonSidecar,
  waitForDaemonHealth,
} from "./daemon";
import { relaySettingFile, readStoredRelayUrl, readStoredWebAppUrl, writeStoredRelayUrl, writeStoredWebAppUrl } from "./relaystore";
import { relayUrlProblems, resolveRelayUrl } from "./relaysetting";
import { resolveWebAppUrl, webAppUrlProblems } from "./webappurl";
import { initDesktopLog, log, logError } from "./desktop-log";
import { initSidecarLog } from "./sidecar-log";
import { phonePaired, type PairingState } from "./pairing";
import { versionMismatch } from "./versions";
import { applyAppUserModelId, daemonNotify, NOTIFY_BACK_BODY, NOTIFY_DOWN_BODY, NOTIFY_TITLE, type DaemonHealth } from "./notify";
import { deepLinkFromArgv, parseDeepLink } from "./deeplink";
import { externalOpenDecision } from "./extlink";
import { guestAttachDecision, guestNavigationDecision } from "./webviewguard";
import { permissionDecision, requestingScheme } from "./permissions";
import { daemonTooltip, loginItemSupported, logsDirPath, openLogsFolder, trayIconSource } from "./tray";
import { badgePlan, type BadgePlan } from "./badge";
import { CLOSE_HINT_LOG, closeHintPlan, hintFlagPath, readHintFlag, writeHintFlag } from "./closehint";
import { checkForUpdatesOnBoot, updatesEnabled, updateMenuLabel, type UpdateDialogSinks, type UpdateStatus } from "./update";
import { menuSpec, type MenuItemSpec } from "./menu";
import { nextCheckDelayMs } from "./updateschedule";
import { loadWindowBounds, saveWindowBounds, WINDOW_MIN, windowStateFile } from "./window-state";
import { installFatalErrorHandlers, onRendererGone, ReloadGuard } from "./crash";
import { clientLogsDir, writeCrashReport } from "./crash-log";
import {
  instanceRecordPath,
  isProcessAlive,
  keeperPidFromEnv,
  processStartedBefore,
  readInstanceRecord,
  writeInstanceRecord,
  zombieWarning,
} from "./instances";
import { buildDiagnosticReport, DIAG_LOG_TAIL, DIAG_SIDECAR_TAIL } from "./diagnostics";
import { desktopLogFile } from "./desktop-log";
import { sidecarLogFile } from "./sidecar-log";

// Tray fallback glyph (P3-009): since P3-015 the tray prefers the monochrome
// template asset build/trayTemplate.png (generated by scripts/make-icon.mjs),
// which macOS recolors to match the light/dark menu bar. This data-URL stays
// as the degradation path when that asset is missing or empty.
const TRAY_ICON_PNG =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAPUlEQVR4nGNgoAWQkJD+jw2TrZEog5AVKB2Nw4rxGkJIM7ohZGnGacioAVQwgOJopEpCojgpE2MQQY3kAABalSlohfDTkQAAAABJRU5ErkJggg==";

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let daemonStopped = false;
// P2-021: set by every real quit path (tray Quit, before-quit, will-quit) so
// the window's close handler can tell "user closed the window" apart from
// "app is shutting down" — close-to-tray on every platform.
let quitting = false;
// P3-019: latest update-check decision (null = no check resolved yet). Kept in
// the main process and surfaced only through the tray menu — no new IPC.
let lastUpdateStatus: UpdateStatus | null = null;
// P3-053: last unread count the renderer pushed over ocr:unread — the state
// the dock badge is (or would be) showing. Exposed via app:unreadBadge for
// the desktop harness; never derived from the OS itself.
let lastUnreadBadge = 0;
// P2-155: periodic update recheck. The app can stay alive for weeks with the
// window closed to the tray (P2-152), so the boot-only check would pin the
// installed version forever. `updateRecheckTimer` holds the single pending
// setTimeout (cleared before any reschedule — a tray re-check during a
// scheduled wait replaces it, never stacks); `updateFeedFailures` counts
// consecutive dead-feed checks and drives the 15 min → 6 h backoff.
let updateRecheckTimer: NodeJS.Timeout | null = null;
let updateFeedFailures = 0;

// P3-012: file logging installed before anything can log — console.* in the
// packaged app is invisible to the stage-5 user (no terminal), so every
// main-process line now also lands in userData/logs/desktop.log (~1MB cap,
// one rotated file kept). Write failures are log-only and never throw.
// P1-051: harness escape hatch (tools/desktop.mjs) — a hermetic launch points
// userData at a temp dir before anything reads a path under it (file log,
// window-state, single-instance lock). Same test-only OCR_* hatch pattern.
const harnessUserData = process.env.OCR_USER_DATA_DIR;
if (harnessUserData) {
  mkdirSync(harnessUserData, { recursive: true });
  app.setPath("userData", harnessUserData);
}
// P1-081: hermetic e2e marker (tools/desktop.mjs harness). The gate drives the
// app exclusively through webContents (page.evaluate/screenshots via CDP), so
// the window must never surface on the operator's screen: hidden on boot,
// showMainWindow() is a no-op and the renderer keeps painting with
// paintWhenInitiallyHidden. Same test-only OCR_* hatch policy.
const HERMETIC_E2E = !!process.env.OCR_DESKTOP_SESSION;
initDesktopLog(app.getPath("userData"));
// P3-018: the daemon sidecar's stdout/stderr (JSONL lines) is teed to
// userData/logs/daemon-sidecar.log (~1MB cap, one rotated file kept). Must be
// installed before the first spawnChild — later, early daemon output would be
// lost in the packaged app. Write failures are log-only and never throw.
initSidecarLog(app.getPath("userData"));
// P3-011/P1-050: a main-process exception used to crash Electron without
// will-quit, killing the daemon sidecar with no cleanup. Installed before
// anything can throw, so even boot-time failures quit through the graceful
// path. Fatal errors route through the file logger (sink injection) AND land
// a crash report file under ~/.opencode-remote/pilot/client-logs/ (P1-050,
// best-effort: a full disk never takes the shell down).
function reportCrash(kind: string, detail: string): void {
  const file = writeCrashReport(clientLogsDir(homedir()), kind, detail, app.getVersion());
  if (file) log(`[desktop] crash report written: ${file}`);
  else logError("[desktop] crash report write failed (continuing, file logging has the detail)");
}

/** Gathers everything buildDiagnosticReport needs (all best-effort, log-only). */
function buildDiagnostics(): string {
  let logTail: string[] = [];
  try {
    logTail = readFileSync(desktopLogFile(app.getPath("userData")), "utf8")
      .split("\n")
      .filter(Boolean)
      .slice(-DIAG_LOG_TAIL);
  } catch {
    // no log file yet (fresh install) — the bundle just skips the tail
  }
  // P2-163: the daemon-sidecar.log tail rides along in the bundle — it is the
  // only daemon JSONL record in the packaged app and is redacted on disk
  // (P2-160). Missing/unreadable file → empty array → the builder renders the
  // "(sem log do sidecar)" placeholder line.
  let sidecarLogTail: string[] = [];
  try {
    sidecarLogTail = readFileSync(sidecarLogFile(app.getPath("userData")), "utf8")
      .split("\n")
      .filter(Boolean)
      .slice(-DIAG_SIDECAR_TAIL);
  } catch {
    // no sidecar log yet (fresh install) — the bundle shows the placeholder
  }
  let crashFiles: string[] = [];
  try {
    crashFiles = readdirSync(clientLogsDir(homedir()))
      .filter((f) => f.startsWith("crash-") && f.endsWith(".txt"))
      .sort()
      .slice(-10);
  } catch {
    // no crash folder yet
  }
  const { reconnecting, attempts } = reconnectState();
  return buildDiagnosticReport({
    appVersion: app.getVersion(),
    electronVersion: process.versions.electron ?? "?",
    platform: `${process.platform} ${process.arch}`,
    locale: app.getLocale(),
    packaged: app.isPackaged,
    userData: app.getPath("userData"),
    daemon: {
      healthy: trayHealthy === true,
      down: isDaemonDown(),
      reconnecting,
      attempts,
      port: activeDaemonPort(),
      portReason: daemonPortReason(),
    },
    logTail,
    sidecarLogTail,
    crashFiles,
    updateStatus: lastUpdateStatus,
  });
}

installFatalErrorHandlers(app, {
  error: (line) => {
    logError(line);
    reportCrash("uncaught", line);
  },
});
// P3-011: shared crash-recovery budget — max 3 renderer reloads per 60s.
const rendererReloadGuard = new ReloadGuard();

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  // P2-069: a second real instance must never paint its own (white) window on
  // top of the running one. Quit quietly — the winner receives second-instance
  // and focuses itself — after explaining the verdict in the shared desktop.log
  // (same userData, so the line lands right where support looks first).
  const holder = readInstanceRecord(instanceRecordPath(app.getPath("userData")));
  log(
    `[desktop] another instance already owns this userData` +
      (holder ? ` (pid ${holder.pid}, started ${new Date(holder.startedAt).toISOString()})` : "") +
      ` — focusing it instead of opening a second window`,
  );
  app.quit();
} else {
  // P3-020: Windows toasts are dropped by the OS unless the AppUserModelID is
  // set (must match electron-builder.yml's appId); must happen before ready.
  // macOS resolves the identity via Info.plist, so the call is skipped there.
  applyAppUserModelId(app, process.platform);
  // P2-069 leash (b, test-only hatch): the hermetic harness (tools/desktop.mjs)
  // passes its own pid via OCR_KEEPER_PID. If the keeper dies — SIGKILL from a
  // pre-flight reaper, an OOM, anything — the Electron instance used to leak
  // forever (the 32h white-window zombie). The app now watches the keeper and
  // quits within WATCHDOG_MS of its death. Never set outside the harness.
  const keeperPid = keeperPidFromEnv(process.env);
  if (keeperPid) startKeeperLeash(keeperPid);
  // P3-014: OS-level registration for opencode-remote:// pair links. Packaged
  // builds only — a dev run must never steal the OS handler — and only on the
  // platforms that support the flow (macOS open-url, Windows second-instance
  // argv). Registration covers the packaged app alone; electron-builder
  // declares the scheme in the bundle (protocols: in electron-builder.yml).
  if (app.isPackaged && (process.platform === "darwin" || process.platform === "win32")) {
    app.setAsDefaultProtocolClient("opencode-remote");
  }
  // macOS: Finder/LaunchServices hands the URL over before ready on a cold
  // start — register early so the very first launch already pairs.
  app.on("open-url", (event, url) => {
    event.preventDefault();
    handleDeepLink(url);
  });
  app.on("second-instance", (_event, argv) => {
    showMainWindow();
    // Windows: the OS spawns a second process whose argv carries the URL;
    // the single-instance winner receives it here.
    handleDeepLink(deepLinkFromArgv(argv));
  });
  app
    .whenReady()
    .then(() => onReady())
    .catch((err) => {
      logError("[desktop] startup failed:", err);
      app.quit();
    });
}

// --- instance hygiene (P2-069) ------------------------------------------------
// Same-userData zombie detection: the boot-record file (instances.ts) survives
// crashes and SIGKILLs, so an alive holder with an earlier start at boot time
// is exactly the "white window lived for 32h" incident. Log-only: killing other
// processes is the pre-flight reaper's job (scripts/e2e-orphans.ts), never the
// shell's.

/** Logs a zombie warning for a still-alive earlier instance (if any), then
 * records this boot as the current holder of the userData. */
function logInstanceBoot(): void {
  const file = instanceRecordPath(app.getPath("userData"));
  const nowMs = Date.now();
  const previous = readInstanceRecord(file);
  if (previous) {
    const alive = isProcessAlive(previous.pid);
    const warn = zombieWarning({
      previous,
      currentPid: process.pid,
      nowMs,
      alive,
      startedBeforeCurrent: alive ? processStartedBefore(previous.pid, nowMs) : null,
    });
    if (warn) log(`[desktop] ${warn}`);
  }
  if (!writeInstanceRecord(file, { pid: process.pid, startedAt: nowMs })) {
    logError("[desktop] instance boot record write failed (continuing)");
  }
}

/** P2-069 (b): hermetic-instance leash — quit when the keeper pid disappears
 * (see the OCR_KEEPER_PID note in the lock branch above). The graceful quit can
 * stall (the harness keeper carries the same 12s SIGKILL fallback for the same
 * reason), so a 4s grace is followed by app.exit() — the leash must never
 * leave a zombie behind, and it only ever runs in harness instances. */
function startKeeperLeash(keeperPid: number): void {
  const WATCHDOG_MS = 5_000;
  const LEASH_GRACE_MS = 4_000;
  const timer = setInterval(() => {
    if (isProcessAlive(keeperPid)) return;
    clearInterval(timer);
    log(`[desktop] keeper pid ${keeperPid} is gone — quitting hermetic instance (P2-069)`);
    app.quit();
    setTimeout(() => {
      log("[desktop] leash grace elapsed without a clean quit — exiting (P2-069)");
      app.exit(0);
    }, LEASH_GRACE_MS).unref();
  }, WATCHDOG_MS);
}

// --- auto-update flow (P1-050) ------------------------------------------------
// One entry point shared by the boot check and the tray's "Check for updates"
// item. The heavy lifting (feed fetch, decision, download wiring, consent
// dedupe) lives in src/update.ts; here only the Electron-facing sinks are
// wired. Listener attachment is idempotent per updater instance there, so
// calling this repeatedly never stacks dialogs or stale handlers.

/** Consent dialog the updater module calls back into; applying the downloaded
 * release is the updater's own quitAndInstall (Squirrel.Mac swaps the bundle). */
const updateDialogSinks: UpdateDialogSinks = {
  askInstall: async (version) => {
    const options: Electron.MessageBoxOptions = {
      type: "info",
      title: "Update ready",
      message: `Version ${version} is ready to install`,
      detail: "Restart OpenCode Remote now to apply the update. Your pairing and conversations are kept.",
      buttons: ["Restart now", "Later"],
      defaultId: 0,
      cancelId: 1,
      noLink: true,
    };
    const { response } =
      mainWindow && !mainWindow.isDestroyed()
        ? await dialog.showMessageBox(mainWindow, options)
        : await dialog.showMessageBox(options);
    return response === 0 ? "install" : "later";
  },
};

function runUpdateCheck(source: string): void {
  void checkForUpdatesOnBoot({
    dialog: updateDialogSinks,
    // P2-131 (round-2 review): yml feeds have no download engine — the manual
    // flow hands the user the release page — but only for an explicit tray
    // re-check. The boot check never auto-opens a browser tab, and update.ts
    // dedupes so each version opens at most once per session.
    openReleasePage:
      source === "tray"
        ? (url) => {
            // P2-178: the release page goes through the same extlink gate as
            // window.open — one external-open path in the whole shell.
            const decision = externalOpenDecision(url);
            if (!decision.allow) {
              logError(`[desktop] release page open refused (reason=${decision.reason})`);
              return;
            }
            void shell.openExternal(decision.href).catch((err) => logError("[desktop] opening release page failed:", err));
          }
        : undefined,
    onStatus: (status, version) => {
      lastUpdateStatus = status;
      refreshTrayMenu();
      // P2-176: the Help menu carries the same status label — rebuild it at
      // the same trigger point so the label never goes stale.
      buildMenu();
      log(`[desktop] update status (${source}): ${status}${version ? ` ${version}` : ""}`);
    },
    // P2-155: the resolved status drives the next scheduled recheck (covers
    // "disabled" too, which never passes through onStatus).
  })
    .then((status) => scheduleNextUpdateCheck(status))
    .catch((err) => {
      logError(`[desktop] update check failed (${source}):`, err);
      // An unexpected throw must not kill the recheck loop forever — treat it
      // as a dead feed so the backoff keeps the periodic check alive.
      scheduleNextUpdateCheck("feed-unreachable");
    });
}

// P2-155: plan and arm the next update check from the status the last one
// resolved with. Derived from checkForUpdatesOnBoot's return value — never
// from onStatus — so the autoUpdater's own update-downloaded emission doesn't
// schedule anything behind the consent flow's back.
function scheduleNextUpdateCheck(status: UpdateStatus): void {
  if (updateRecheckTimer) {
    clearTimeout(updateRecheckTimer);
    updateRecheckTimer = null;
  }
  if (!updatesEnabled()) return;
  if (status === "feed-unreachable" || status === "unrecognized-feed") updateFeedFailures++;
  else updateFeedFailures = 0;
  const delay = nextCheckDelayMs(status, updateFeedFailures, Math.random);
  if (delay == null) return;
  log(`[desktop] update recheck (${status}) in ${Math.round(delay / 60_000)} min`);
  updateRecheckTimer = setTimeout(() => runUpdateCheck("scheduled"), delay);
  updateRecheckTimer.unref?.();
}

async function onReady(): Promise<void> {
  logInstanceBoot();
  buildMenu();
  buildTray();

  // P3-009: real app icon (build/icon.png, generated by scripts/make-icon.mjs)
  // for the macOS dock — on Windows/Linux the BrowserWindow icon below does
  // the job, on macOS the window icon is ignored and the dock is the surface
  // that matters. Missing/empty asset degrades to Electron defaults.
  const icon = appIcon();
  if (icon && process.platform === "darwin" && app.dock) app.dock.setIcon(icon);
  app.setAboutPanelOptions({
    applicationName: "OpenCode Remote",
    applicationVersion: app.getVersion(),
  });

  // P1-050: real update flow — boot check, background download, then a
  // consent dialog before anything restarts. Fire-and-forget: a slow or dead
  // feed must never delay window creation. The resolved status is mirrored
  // into the tray menu by the onStatus callback in runUpdateCheck().
  runUpdateCheck("boot");

  ipcMain.handle("app:version", () => app.getVersion());
  // P1-050: "Copy diagnostic" (Settings) — versions, daemon state, the
  // desktop.log + daemon-sidecar.log tails (P2-163) and the crash-file names
  // in one clipboard-ready bundle.
  // No secrets: the apiToken, allowlist and pairing URI are never included.
  ipcMain.handle("app:diagnostics", () => buildDiagnostics());
  // P2-011: narrow HTTP bridge to the local daemon's /api/browse surface so
  // the renderer can drive the host browser without ever seeing the api token
  // (the 0600 state file stays in this main process). Loopback only, browse
  // routes only — the token never leaves this process.
  ipcMain.handle("app:daemonBrowse", async (_e, req: { path?: string; method?: string; body?: unknown }) => {
    if (!req || typeof req.path !== "string") return null;
    const method = req.method === "POST" ? "POST" : "GET";
    // Anchored, URL-parsed allowlist: `new URL` normalizes ../ traversal into
    // the pathname, so only genuine /api/browse[/action] paths can pass. The
    // outbound URL is rebuilt from the parsed components — the raw renderer
    // string is never forwarded.
    const u = new URL(req.path, "http://127.0.0.1");
    if (!/^\/api\/browse(\/[a-z]+)?$/.test(u.pathname)) return null;
    try {
      const stateFile = join(homedir(), ".opencode-remote", "daemon.json");
      const token = (JSON.parse(readFileSync(stateFile, "utf8")) as { apiToken?: string }).apiToken;
      if (!token) return null;
      const res = await fetch(`http://127.0.0.1:${activeDaemonPort()}${u.pathname}${u.search}`, {
        method,
        headers: { authorization: `Bearer ${token}` },
        body: method === "POST" ? JSON.stringify(req.body ?? {}) : undefined,
        signal: AbortSignal.timeout(45_000),
      });
      // defense in depth: the daemon bounds its payloads, but never trust that
      // blindly — a screenshot is a few MB, so 32 MB is a generous ceiling
      const raw = await res.arrayBuffer();
      if (raw.byteLength > 32 * 1024 * 1024) return null;
      return { status: res.status, contentType: res.headers.get("content-type") ?? "", body: Buffer.from(raw).toString("base64") };
    } catch (err) {
      logError("[desktop] daemonBrowse failed:", err);
      return null;
    }
  });
  // P2-048: Mission Control read feed + human takeover. Same trust shape as
  // app:daemonBrowse above — the apiToken never leaves this process and the
  // renderer-provided path is URL-parsed and matched against a narrow,
  // anchored allowlist: pilot forensic reads (GET) and the takeover action
  // (POST), nothing else.
  ipcMain.handle("app:daemonApi", async (_e, req: { path?: string; method?: string; body?: unknown }) => {
    if (!req || typeof req.path !== "string") return null;
    const method = req.method === "POST" ? "POST" : req.method === "DELETE" ? "DELETE" : "GET";
    const u = new URL(req.path, "http://127.0.0.1");
    // mission v2: the read-only mission card (GET pilot-mission) and the
    // "end mission" action (DELETE /api/mission) join the allowlist
    const okPath =
      method === "GET"
        ? /^\/api\/pilot-(forensic(\/timeline)?|shot|mission)$/.test(u.pathname)
        : method === "DELETE"
          ? /^\/api\/mission$/.test(u.pathname)
          : /^\/api\/pilot-takeover$/.test(u.pathname);
    if (!okPath) return null;
    try {
      const stateFile = join(homedir(), ".opencode-remote", "daemon.json");
      const token = (JSON.parse(readFileSync(stateFile, "utf8")) as { apiToken?: string }).apiToken;
      if (!token) return null;
      const res = await fetch(`http://127.0.0.1:${activeDaemonPort()}${u.pathname}${u.search}`, {
        method,
        headers: { authorization: `Bearer ${token}` },
        body: method === "POST" ? JSON.stringify(req.body ?? {}) : undefined,
        signal: AbortSignal.timeout(45_000),
      });
      const raw = await res.arrayBuffer();
      if (raw.byteLength > 32 * 1024 * 1024) return null;
      return { status: res.status, contentType: res.headers.get("content-type") ?? "", body: Buffer.from(raw).toString("base64") };
    } catch (err) {
      logError("[desktop] daemonApi failed:", err);
      return null;
    }
  });
  // P1-061: local direct mode — the renderer dials the daemon's loopback WS
  // itself (ws://127.0.0.1:<port>/ws?token=…) instead of riding the relay.
  // This deliberately relaxes the "renderer never sees the apiToken" rule:
  // the renderer is a same-user process, the token is only valid on loopback
  // and the E2E client is an authorized peer of the daemon anyway (the
  // handshake crypto stays intact). Trade-off documented in docs/security.md.
  // P1-070: the link now also carries room + ecdhPub so the renderer can
  // derive the local pairing with zero pairing-uri round-trips — still
  // loopback-only, same-user trust domain (the 0600 state file).
  ipcMain.handle("app:localLink", () => {
    const raw = readDaemonState();
    if (!raw?.apiToken) return null;
    const portReason = daemonPortReason();
    return {
      port: activeDaemonPort(),
      token: raw.apiToken,
      room: raw.room,
      ecdhPub: raw.ecdhPub,
      // Absent (not null) before the one-shot port resolution — matches the
      // declared optional contract in preload's LocalLink.
      ...(portReason !== null ? { portReason } : {}),
    };
  });
  // Boot pairing URI captured from the daemon sidecar's stdout (null when the
  // daemon was reused or hasn't printed it yet) — lets the renderer auto-pair.
  // P1-070: in local mode the URI hunt is exactly the bug this fixes — a fresh
  // instance must open the chat, never the QR ceremony. It stays null until
  // the user explicitly opts into remote pairing (Settings / deep link).
  ipcMain.handle("app:pairUrl", () => {
    if (localMode && !remotePairingRequested) return null;
    return getPairUrl();
  });
  // P1-070: explicit remote-pairing opt-in/out (Settings action; the QR
  // overlay's dismiss turns it back off). In-memory only — a restart always
  // boots back into local mode.
  ipcMain.handle("app:setRemotePairing", (_e, on: unknown) => {
    remotePairingRequested = on === true;
    // P1-056 (fable #2): snapshot the paired state AT REQUEST TIME. The poll's
    // auto-reset ("a phone joining ends the request") must only fire on the
    // unpaired→paired TRANSITION — otherwise, with devices already paired,
    // every tick cancelled an explicit re-pair request before the QR existed
    // (the dead "Celular" pane).
    if (on === true) remotePairingStartedPaired = pairedNow();
    if (on !== true) remotePairingStartedPaired = false;
    log(`[desktop] remote pairing requested: ${remotePairingRequested}`);
    void refreshPairingState();
    return true;
  });
  // P3-014: late pull for opencode-remote:// pair links. A renderer mounting
  // after the OS already handed over the URL (cold start via open-url) reads
  // the cached value here; consumed once so a stale link can't loop around.
  ipcMain.handle("app:deepLink", () => {
    const uri = lastDeepLink;
    lastDeepLink = null;
    return uri;
  });
  // P2-007: first-run pairing state for the renderer's QR overlay. The main
  // process polls the daemon (see startPairingWatcher) and caches the result;
  // the sandboxed renderer only ever sees this derived state — never the
  // apiToken, allowlist file or raw HTTP responses.
  ipcMain.handle("app:pairingState", () => pairingState);
  // P1-053: one-click recovery from the daemon-down banner — the same manual
  // restart path the tray's "Restart daemon" action uses (P3-017). P2-112:
  // resolves with the real restart outcome so the renderer's trying state and
  // result toast tell the truth instead of a blind fire-and-forget true.
  ipcMain.handle("app:reconnectDaemon", () =>
    restartDaemon().catch((err) => {
      logError("[desktop] banner reconnect failed:", err);
      return false;
    }),
  );
  // P2-187: the phone relay address — read (Settings render) and write (Save /
  // "use the local relay" action). Validation ALWAYS happens here in the main
  // process: a hostile renderer can submit any payload shape and nothing is
  // persisted or applied before relayUrlProblems accepts it. Applying a value
  // restarts the sidecar so the daemon re-emits its pairing URI dialing the
  // new relay; the daemon's own boot preflight (apps/daemon/src/relayurl.ts)
  // stays the final authority on what it actually dials.
  ipcMain.handle("app:relaySetting", () => {
    return resolveRelayUrl(process.env, readStoredRelayUrl(relaySettingFile(app.getPath("userData"))));
  });
  ipcMain.handle("app:setRelayUrl", (_e, payload: unknown) => {
    const file = relaySettingFile(app.getPath("userData"));
    // null / blank string is the "use the local relay" action: clear the
    // stored setting. An exported RELAY_URL still wins when present — the
    // response origin says so, and the UI explains it to the operator.
    if (payload === null || (typeof payload === "string" && payload.trim() === "")) {
      writeStoredRelayUrl(file, null);
      const res = resolveRelayUrl(process.env, null);
      setSidecarRelayUrl(res.url);
      log(`[desktop] relay setting cleared — sidecar RELAY_URL origin ${res.origin}`);
      void restartDaemon();
      return { ok: true, ...res };
    }
    const problems = relayUrlProblems(payload);
    if (problems.length > 0) {
      // Nothing persists, nothing restarts — the UI shows the problem.
      logError(`[desktop] relay setting rejected: ${problems[0]}`);
      return { ok: false, url: typeof payload === "string" ? payload : "", origin: "stored-invalid", problems };
    }
    const stored = (payload as string).trim();
    writeStoredRelayUrl(file, stored);
    const res = resolveRelayUrl(process.env, stored);
    setSidecarRelayUrl(res.url);
    log(`[desktop] relay setting saved — sidecar RELAY_URL origin ${res.origin}`);
    void restartDaemon();
    return { ok: true, ...res };
  });
  // P2-189: the app address the phone opens (step one of the pairing journey)
  // — read + validated write beside the relay setting above, same trust
  // model: validation ALWAYS happens here in the main process and a hostile
  // renderer can submit any payload shape nothing is persisted before
  // webAppUrlProblems accepts it. null/blank clears the stored override so
  // the address falls back to the one derived from the relay.
  ipcMain.handle("app:webAppUrl", () => currentWebAppResolution());
  ipcMain.handle("app:setWebAppUrl", (_e, payload: unknown) => {
    const file = relaySettingFile(app.getPath("userData"));
    if (payload === null || (typeof payload === "string" && payload.trim() === "")) {
      writeStoredWebAppUrl(file, null);
      const res = currentWebAppResolution();
      log(`[desktop] web app setting cleared — origin ${res.origin}`);
      return { ok: true, ...res };
    }
    const problems = webAppUrlProblems(payload);
    if (problems.length > 0) {
      // Nothing persists — the UI shows the problem instead.
      logError(`[desktop] web app setting rejected: ${problems[0]}`);
      return { ok: false, url: typeof payload === "string" ? payload : "", origin: "unavailable", problems };
    }
    writeStoredWebAppUrl(file, (payload as string).trim());
    const res = currentWebAppResolution();
    log(`[desktop] web app setting saved — origin ${res.origin}`);
    return { ok: true, ...res };
  });
  // P3-053/P2-150: dock unread badge — the renderer derives the count
  // (lib/unread.ts) and pushes it on every change. The surface comes from
  // badgePlan (badge.ts): darwin/linux keep app.setBadgeCount, Windows draws
  // a taskbar overlay icon (setBadgeCount is a no-op there). badgePlan also
  // sanitizes the payload, so a hostile/malformed push can never set garbage.
  ipcMain.on("ocr:unread", (_e, n: unknown) => {
    const plan = badgePlan(process.platform, n);
    lastUnreadBadge = plan.count;
    if (plan.kind === "dock") {
      try {
        app.setBadgeCount(plan.count);
      } catch (err) {
        logError("[desktop] setBadgeCount failed:", err);
      }
      return;
    }
    if (plan.kind === "overlay") applyOverlayBadge(plan);
  });
  // P3-053: verification surface for tools/desktop.mjs ipc and the flow test —
  // reports the last count the renderer pushed (not an OS read-back).
  ipcMain.handle("app:unreadBadge", () => lastUnreadBadge);
  // Host self-approval: the desktop shell runs on the same machine that owns
  // daemon.json, so it may add its own client identity to the allowlist. The
  // daemon re-reads the allowlist file on every handshake (fresh read), so
  // this takes effect on the next connect without a daemon restart.
  ipcMain.handle("app:approveClient", (_e, pub: string) => {
    if (typeof pub !== "string" || pub.length < 40 || !/^[A-Za-z0-9+/=]+$/.test(pub)) {
      return false;
    }
    try {
      // P1-070: resolve through stateFilePath() (same file readApiToken/
      // readDaemonState use) so the hermetic gate's OCR_DAEMON_STATE_FILE
      // override is honored everywhere — production paths are identical.
      const file = stateFilePath();
      const raw = JSON.parse(readFileSync(file, "utf8")) as {
        clients?: { pub: string; label?: string; addedAt: string }[];
      };
      raw.clients ??= [];
      if (raw.clients.some((c) => c.pub === pub)) return true;
      raw.clients.push({ pub, label: "desktop-host", addedAt: new Date().toISOString() });
      writeFileSync(file, JSON.stringify(raw, null, 2), { mode: 0o600 });
      return true;
    } catch (err) {
      logError("[desktop] approveClient failed:", err);
      return false;
    }
  });

  // P2-187: resolve the phone relay address (env > stored > default) BEFORE
  // the first spawn so even the initial sidecar (and every respawn) dials the
  // configured relay instead of assuming this machine's loopback.
  setSidecarRelayUrl(
    resolveRelayUrl(process.env, readStoredRelayUrl(relaySettingFile(app.getPath("userData")))).url,
  );

  // Sidecar: boot a local daemon (unless one is already healthy), wait for
  // /api/health before showing the UI. On timeout we still show the UI —
  // it renders its own disconnected state. waitForDaemonHealth reuses the
  // token captured by startDaemonSidecar and aborts early if the child died.
  const daemonReady = await startDaemonSidecar(
    app.getAppPath(),
    app.isPackaged ? process.resourcesPath : undefined,
  );
  const healthOK = daemonReady && (await waitForDaemonHealth());
  if (!healthOK) {
    logError(`[desktop] daemon health not confirmed on :${activeDaemonPort()} — continuing`);
  }
  // P1-070: boot-time local-mode decision. The daemon on this machine shares
  // the trust domain (loopback, same user, 0600 daemon.json) and healthOnce
  // already ran the anti-squatter 401 challenge before the Bearer probe — so
  // when it answers, the pairing ceremony (QR/URI hunt) is a mental-model bug,
  // not a feature. The test-only OCR_DAEMON_FORCE_* hatches keep precedence so
  // hermetic gate runs stay deterministic even on a machine with a real daemon.
  localMode =
    healthOK &&
    readApiToken() !== null &&
    !FORCE_VERSION_MISMATCH &&
    !isDaemonDown() &&
    !reconnectState().reconnecting;
  if (localMode) log("[desktop] local daemon proved healthy — pairing ceremony skipped (P1-070)");

  // P2-182: single permission path for the whole shell, registered
  // unconditionally — the Electron default grants several permissions
  // silently, and since the bundle is signed with camera/mic usage
  // descriptions a third-party page in the Browser pane would make the OS
  // show the request as our product asking. Both handlers consult the same
  // pure decision: only media, clipboard-sanitized-write and fullscreen,
  // only for the shell's own origin. Refusals are logged with the
  // permission name + requester scheme only, never the full URL, so user
  // navigation cannot leak into desktop.log.
  // P2-117 test hatch (scripts/desktop-flow.test.ts): the camera-block env
  // denies media even for the shell origin so the scanner's unavailable
  // state is provable on hosts that do have a camera (no macOS TCC prompt in
  // gate runs). Same test-only policy as OCR_DAEMON_FORCE_* — never set in
  // production; its only effect is the cameraBlocked flag below.
  const permissionCtx = {
    devUrl: process.env.OCR_WEB_URL,
    cameraBlocked: process.env.OCR_DESKTOP_CAMERA_BLOCK === "1",
  };
  session.defaultSession.setPermissionRequestHandler((_wc, permission, callback, details) => {
    const decision = permissionDecision(permission, details?.requestingUrl, permissionCtx);
    if (!decision.allow) {
      logError(`[desktop] permission denied: ${permission} ${requestingScheme(details?.requestingUrl)} — ${decision.reason}`);
    }
    callback(decision.allow);
  });
  session.defaultSession.setPermissionCheckHandler(
    (_wc, permission, requestingOrigin) => permissionDecision(permission, requestingOrigin, permissionCtx).allow,
  );

  // P2-184: the single guest path. Every webContents created from here on is
  // classified once by type: a Browser-pane <webview> guest has its main-frame
  // navigations (link clicks, redirects, meta refreshes) checked against the
  // pure decision — only http/https pass, so a redirect can never render local
  // user files inside the pane — and its window.open denied outright; the
  // shell window gets the will-attach-webview hook that forces the sanitized
  // guest preferences over whatever the renderer declared and drops any
  // renderer-declared preload. Refusals log scheme + reason only, never the
  // URL (same policy as the P2-178/P2-182 gates).
  app.on("web-contents-created", (_event, contents) => {
    if (contents.getType() === "webview") {
      const guardGuestNavigation = (navEvent: { preventDefault(): void }, url: string): void => {
        const decision = guestNavigationDecision(url);
        if (!decision.allow) {
          navEvent.preventDefault();
          logError(`[desktop] guest navigation refused (scheme=${requestingScheme(url)}) — ${decision.reason}`);
        }
      };
      contents.on("will-navigate", guardGuestNavigation);
      contents.on("will-redirect", guardGuestNavigation);
      contents.setWindowOpenHandler(() => ({ action: "deny" }));
    } else if (contents.getType() === "window") {
      contents.on("will-attach-webview", (attachEvent, webPreferences, params) => {
        const decision = guestAttachDecision(params.src, webPreferences, webPreferences.preload);
        if (!decision.allow) {
          attachEvent.preventDefault();
          logError(`[desktop] guest attach refused (scheme=${requestingScheme(params.src)}) — ${decision.reason}`);
          return;
        }
        Object.assign(webPreferences, decision.webPreferences);
        // Electron's own hardening recipe: a renderer-declared preload must
        // never survive the attach.
        delete webPreferences.preload;
      });
    }
  });

  createWindow();
  startPairingWatcher();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
    else showMainWindow();
  });
  app.on("window-all-closed", () => {
    // P2-021: with close-to-tray the window is hidden on close, so this only
    // fires when windows are really gone (win.destroy, crash cleanup).
    // Keep the tray alive on macOS (convention); quit elsewhere.
    if (process.platform !== "darwin") app.quit();
  });
  app.on("before-quit", () => {
    // Every app.quit() path (tray Quit, menu role, window-all-closed) is a
    // real quit: the close handler must let the window die instead of hiding.
    quitting = true;
  });
  app.on("will-quit", (event) => {
    // P2-155: a pending periodic recheck must not outlive the app.
    if (updateRecheckTimer) {
      clearTimeout(updateRecheckTimer);
      updateRecheckTimer = null;
    }
    // Encerra o daemon que subimos antes de sair (idempotente).
    if (daemonStopped) return;
    event.preventDefault();
    quitting = true;
    if (pairingTimer) clearInterval(pairingTimer);
    void stopDaemonSidecar().then(() => {
      daemonStopped = true;
      app.quit();
    });
  });
}

// --- opencode-remote:// deep links (P3-014) ----------------------------------
// The OS hands the shell a raw URL (macOS open-url, Windows second-instance
// argv) whenever an install/invite page opens the app. Validation is pure
// (src/deeplink.ts): only a well-formed pair URI passes. A valid link is
// cached for the renderer's late pull (app:deepLink) and pushed to any live
// window; the renderer routes it through the same parsePairingUri path as
// paste-pairing — no new crypto.

let lastDeepLink: string | null = null;

function handleDeepLink(raw: unknown): void {
  const uri = parseDeepLink(raw);
  if (!uri) return;
  // Logged without the URI: it carries the room's pairing key material and
  // the desktop.log lives on disk unencrypted.
  log("[desktop] deep link accepted (opencode-remote://pair)");
  lastDeepLink = uri;
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) win.webContents.send("ocr:deep-link", uri);
  }
}

// --- first-run pairing watcher (P2-007) --------------------------------------
// After daemon health OK, poll the loopback API every 3s: while no phone is
// paired, fetch the boot pairing URI, render it as a PNG data-URL and hand the
// whole state to the renderer, which draws the QR overlay. As soon as the
// allowlist holds a non-host device (the phone scanned the QR), the overlay
// leaves and the chat shows. Read-only end to end: the allowlist itself is
// only ever read, never written here.

const PAIRING_POLL_MS = 3_000;
const PROBE_TIMEOUT_MS = 2_000;

// P3-054: test-only escape hatch (tools/desktop.mjs harness + builder shots):
// reports an intentionally older daemon version so the mismatch banner renders
// deterministically. Never set in production — same policy as OCR_DAEMON_FORCE_*.
const FORCE_VERSION_MISMATCH = process.env.OCR_DAEMON_FORCE_VERSION_MISMATCH === "1";

let pairingState: PairingState | null = null;
let pairingTimer: NodeJS.Timeout | null = null;

// P1-070: local mode is decided once at boot (see onReady); the explicit
// remote-pairing request lives in memory only — a restart boots back local.
let localMode = false;
let remotePairingRequested = false;
/** P1-056: paired state when the explicit request landed — the poll's
 * auto-reset only fires on the unpaired→paired transition. */
let remotePairingStartedPaired = false;
function pairedNow(): boolean {
  return pairingState?.phonePaired ?? false;
}

/** P1-070: degraded states keep the local marker so a failed poll never
 * resurrects the QR ceremony in local mode — the renderer keeps auto-connecting
 * once the daemon answers again (P1-053 semantics, no re-pairing). */
function withLocalMode(state: PairingState): PairingState {
  return localMode && !remotePairingRequested ? { ...state, mode: "local" } : state;
}

/** Placeholder state while the sidecar is down for good (P2-017): no QR (the
 * old room/keys are dead with the daemon), just the "daemon down" flag.
 * P2-140: carries the exit classifier's verdict so the renderer can say WHY
 * the daemon died, not only that it gave up. */
function daemonDownState(): PairingState {
  const exit = sidecarExitInfo();
  return {
    uri: null,
    qrDataUrl: null,
    devices: 0,
    phonePaired: false,
    daemonDown: true,
    sidecarExit: exit ? { kind: exit.kind, reason: exit.reason, hint: exit.hint } : undefined,
  };
}

/** P1-053: adopted daemon (reused launchd/CLI install) lost mid-run — the
 * shell keeps probing forever, so this is an active, recoverable state: the
 * yellow "reconnecting…" banner with the attempt counter. uri stays null so
 * the QR overlay can never open from it, and nothing re-pairs on recovery. */
function reconnectingState(): PairingState {
  const { attempts } = reconnectState();
  return {
    uri: null,
    qrDataUrl: null,
    devices: 0,
    phonePaired: false,
    reconnecting: true,
    reconnectAttempts: attempts,
  };
}

function setPairingState(next: PairingState | null): void {
  const changed = JSON.stringify(next) !== JSON.stringify(pairingState);
  pairingState = next;
  // Push so the overlay reacts within one poll; the renderer also pulls
  // (invoke) on mount — a fresh window never waits for a change. Broadcast to
  // every window: createWindow() doesn't track a single mainWindow handle.
  if (changed) {
    for (const win of BrowserWindow.getAllWindows()) {
      if (!win.isDestroyed()) win.webContents.send("ocr:pairing-state", pairingState);
    }
  }
}

// --- tray tooltip as sidecar health indicator (P3-007) -----------------------
// Fed by the pairing watcher's 3s poll below: the last authenticated request
// against the daemon decides ok/down. Deduplicated so the tooltip is only
// rewritten on actual transitions.

let trayHealthy: boolean | null = null;

function setTrayHealthy(healthy: boolean): void {
  if (trayHealthy === healthy) return;
  trayHealthy = healthy;
  tray?.setToolTip(daemonTooltip(healthy));
  log(`[desktop] tray tooltip: ${daemonTooltip(healthy)}`);
}

// --- native daemon notifications (P3-013) -------------------------------------
// Fed by the same poll as the tray tooltip: when the sidecar's respawn budget
// is exhausted (isDaemonDown() true) the window may be closed to the tray, and
// a tray tooltip alone never reaches a non-technical user — so each real
// transition fires a native notification instead. Decision logic is pure
// (src/notify.ts) and tested in scripts/unit.test.ts.

let daemonHealthObserved: DaemonHealth | null = null;

function observeDaemonHealth(down: boolean): void {
  const next: DaemonHealth = down ? "down" : "healthy";
  const decision = daemonNotify(daemonHealthObserved, next);
  daemonHealthObserved = next;
  if (decision.notify === "none") return;
  // Best-effort only: an unsupporting platform, a full disk or a denied
  // permission must never take the shell down — the poll continues regardless.
  try {
    if (!Notification.isSupported()) return;
    const body = decision.notify === "down" ? NOTIFY_DOWN_BODY : NOTIFY_BACK_BODY;
    new Notification({ title: NOTIFY_TITLE, body, silent: false }).show();
    log(`[desktop] notification: ${body}`);
  } catch (err) {
    logError("[desktop] daemon notification failed:", err);
  }
}

/** One-time close-to-tray hint (P2-152): since P2-021 a plain close hides the
 * window with the daemon sidecar and tray still alive, but nothing said so —
 * the leigo user closes the window and believes the app is gone. The first
 * non-quitting close fires ONE native notification and stamps a flag in
 * userData; decision logic is pure (src/closehint.ts) and tested in
 * scripts/unit.test.ts. Entirely best-effort — same discipline as
 * observeDaemonHealth(): nothing here may block the hide() above it, and the
 * real quit path (quitting === true) never reaches this. */
function maybeShowCloseHint(): void {
  try {
    const file = hintFlagPath(app.getPath("userData"));
    const plan = closeHintPlan(process.platform, readHintFlag(() => readFileSync(file, "utf8")));
    if (plan.kind === "none") return;
    if (!Notification.isSupported()) {
      log("[desktop] close hint skipped: notifications unsupported");
      return;
    }
    new Notification({ title: plan.title, body: plan.body, silent: true }).show();
    log(CLOSE_HINT_LOG);
    // Stamp only after the notification actually went out — a platform without
    // support never burns the one-shot chance.
    if (!writeHintFlag((value) => writeFileSync(file, value, "utf8"))) {
      log("[desktop] close hint flag write failed");
    }
  } catch (err) {
    logError("[desktop] close hint failed:", err);
  }
}

/** P3-054: deterministic mismatch state for the harness (see the hatch note
 * above). uri/qrDataUrl stay null so the QR overlay can never open from it —
 * same shape discipline as reconnectingState(). */
function forcedMismatchState(): PairingState {
  return {
    uri: null,
    qrDataUrl: null,
    devices: 0,
    phonePaired: false,
    appVersion: app.getVersion(),
    daemonVersion: "0.0.1-force",
    versionMismatch: true,
  };
}

/**
 * P2-189: the address the phone opens (step one of the pairing journey),
 * resolved fresh on every call: the relay address as resolveRelayUrl sees it
 * (env > stored > default) feeds the derivation unless the operator stored an
 * explicit app address, which wins. Pure decision — resolveWebAppUrl in
 * webappurl.ts; no QR is minted here when the resolution has problems.
 */
function currentWebAppResolution() {
  const file = relaySettingFile(app.getPath("userData"));
  const relay = resolveRelayUrl(process.env, readStoredRelayUrl(file));
  return resolveWebAppUrl(relay, readStoredWebAppUrl(file));
}

async function refreshPairingState(): Promise<void> {
  // Test-only override first: the hermetic harness has no apiToken, so without
  // this the happy path (the only place a real mismatch is detected) is
  // unreachable and the banner could never render deterministically.
  if (FORCE_VERSION_MISMATCH) {
    setPairingState(forcedMismatchState());
    return;
  }
  const token = readApiToken();
  if (!token) {
    // Cannot prove health without the token — report down until proven ok.
    setTrayHealthy(false);
    observeDaemonHealth(isDaemonDown());
    if (isDaemonDown()) {
      setPairingState(withLocalMode(daemonDownState()));
    } else if (reconnectState().reconnecting) {
      setPairingState(withLocalMode(reconnectingState()));
    } else {
      setPairingState(null);
    }
    return;
  }
  const base = `http://127.0.0.1:${activeDaemonPort()}`;
  const headers = { authorization: `Bearer ${token}` };
  try {
    const devRes = await fetch(`${base}/__ocr/devices`, { headers, signal: AbortSignal.timeout(PROBE_TIMEOUT_MS) });
    if (!devRes.ok) throw new Error(`devices ${devRes.status}`);
    const { devices } = (await devRes.json()) as { devices?: { pub: string; label?: string }[] };
    if (!Array.isArray(devices)) throw new Error("malformed devices payload");
    setTrayHealthy(true);
    // The daemon answers (adopted or sidecar) — control is back.
    observeDaemonHealth(false);

    // P3-054: keep the live daemon's version in the state so the renderer can
    // flag a stale adopted daemon (older or different major than the shell).
    // One loopback call per poll; unknown version degrades to "no banner".
    // (The FORCE_VERSION_MISMATCH hatch never reaches this path — it returns
    // the deterministic forced state at the top of refreshPairingState.)
    // P2-138: the same /api/health answer carries the upstream opencode
    // detail (P2-135 classifier verdict) — propagated additively next to the
    // version fields so the renderer can explain WHY the agent is unreachable.
    const appVersion = app.getVersion();
    const { version: daemonVersion, opencode } = await fetchDaemonHealth(token);
    const mismatch = versionMismatch(appVersion, daemonVersion);
    if (mismatch) {
      log(`[desktop] daemon version mismatch: daemon ${daemonVersion ?? "?"} · app ${appVersion}`);
    }

    const paired = phonePaired(devices);
    // P1-070: a phone joining the allowlist ends the explicit remote request —
    // the next tick returns to the quiet local state. P1-056: only on the
    // unpaired→paired transition — with devices already paired the request is
    // the user's explicit "pair another one" and must survive the tick.
    if (paired && !remotePairingStartedPaired) remotePairingRequested = false;
    // Local mode never hunts for a pairing URI: uri/qrDataUrl stay null so the
    // QR overlay can never open from it (the boot-ceremony bug this fixes).
    // The explicit remote request (Settings) restores the legacy fetch below.
    const quietLocal = localMode && !remotePairingRequested;
    let uri: string | null = null;
    let qrDataUrl: string | null = null;
    // P1-056: an explicit remote request ("Celular" pane) fetches the QR even
    // when a phone is already paired — pairing a SECOND device is legitimate.
    if (!quietLocal && (!paired || remotePairingRequested)) {
      uri = pairingState?.uri ?? null;
      qrDataUrl = pairingState?.qrDataUrl ?? null;
      // Only fetch/refresh while the overlay may still be needed; once a phone
      // is paired the QR is dead weight.
      const uriRes = await fetch(`${base}/__ocr/pairing-uri`, {
        headers,
        signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
      });
      if (!uriRes.ok) throw new Error(`pairing-uri ${uriRes.status}`);
      uri = ((await uriRes.json()) as { uri?: string }).uri ?? null;
      if (uri) qrDataUrl = await QRCode.toDataURL(uri, { margin: 1, width: 480 });
    }
    // P2-189: step one rides the same tick — the address the phone opens
    // before there is a pairing QR to scan. Additive field; the QR is minted
    // by the same QRCode.toDataURL ONLY when the resolution is problem-free
    // (a problem means the reason travels instead and no QR is generated).
    const webAppRes = currentWebAppResolution();
    const webApp = {
      url: webAppRes.url,
      origin: webAppRes.origin,
      reason: webAppRes.problems[0] ?? "",
      qrDataUrl:
        webAppRes.url !== "" && webAppRes.problems.length === 0
          ? await QRCode.toDataURL(webAppRes.url, { margin: 1, width: 480 })
          : null,
    };
    setPairingState({
      mode: quietLocal ? "local" : remotePairingRequested ? "remote" : undefined,
      uri,
      qrDataUrl,
      devices: devices.length,
      deviceList: devices.map((d) => ({ label: d.label ?? "device" })),
      phonePaired: paired,
      appVersion,
      daemonVersion,
      versionMismatch: mismatch,
      opencode: opencode ?? undefined,
      webApp,
    });
  } catch (err) {
    // Daemon down, token rotated or state file wiped: drop the cached state so
    // a stale QR (old room/keys) is never shown. The next healthy tick
    // rebuilds everything from scratch. When the sidecar exhausted its
    // respawn budget (P2-017), tell the renderer instead of staying silent.
    logError(`[desktop] pairing poll failed: ${err instanceof Error ? err.message : err}`);
    setTrayHealthy(false);
    observeDaemonHealth(isDaemonDown());
    if (isDaemonDown()) {
      setPairingState(withLocalMode(daemonDownState()));
    } else if (reconnectState().reconnecting) {
      // P1-053: adopted daemon still being probed — active reconnect state
      // instead of silence, so the UI never falls back to the pairing screen.
      setPairingState(withLocalMode(reconnectingState()));
    } else {
      setPairingState(null);
    }
  }
}

function startPairingWatcher(): void {
  if (pairingTimer) return;
  void refreshPairingState();
  pairingTimer = setInterval(() => void refreshPairingState(), PAIRING_POLL_MS);
}

// P3-009: the packaged app ships build/icon.png inside the asar (files list in
// electron-builder.yml) and dev runs resolve it next to the sources; Electron
// reads images through asar transparently.
function appIcon(): Electron.NativeImage | undefined {
  const path = join(app.getAppPath(), "build", "icon.png");
  if (!existsSync(path)) return undefined;
  const img = nativeImage.createFromPath(path);
  return img.isEmpty() ? undefined : img;
}

// P2-150: the Windows taskbar overlay glyph — the solid disk generated by
// scripts/make-icon.mjs, shipped inside the asar like the tray templates.
// Same degradation as the tray template asset (trayIconSource): a missing or
// unreadable file means no overlay, logged once — never a crash. Memoized so
// a broken install logs a single line instead of one per push.
let overlayBadgeCache: Electron.NativeImage | null | undefined;
function overlayBadgeImage(): Electron.NativeImage | null {
  if (overlayBadgeCache !== undefined) return overlayBadgeCache;
  const path = join(app.getAppPath(), "build", "overlayBadge.png");
  let img: Electron.NativeImage | null = null;
  if (existsSync(path)) {
    const loaded = nativeImage.createFromPath(path);
    if (!loaded.isEmpty()) img = loaded;
  }
  if (!img) log("[desktop] overlay badge asset unavailable — taskbar overlay disabled");
  overlayBadgeCache = img;
  return img;
}

// P2-150: win32 badge surface. A positive count composites the disk onto the
// taskbar icon with the screen-reader description from badgePlan; a zero
// count (or a missing asset degrading to null) clears the overlay.
function applyOverlayBadge(plan: BadgePlan): void {
  const win = mainWindow;
  if (!win || win.isDestroyed()) return;
  const icon = plan.count > 0 ? overlayBadgeImage() : null;
  try {
    win.setOverlayIcon(icon, icon ? plan.description : "");
  } catch (err) {
    logError("[desktop] setOverlayIcon failed:", err);
  }
}

function createWindow(): BrowserWindow {
  // P3-008: restore the last window bounds. loadWindowBounds degrades to the
  // 1280x820 default on a missing/corrupted file, and sanitizeWindowBounds
  // drops bounds that don't intersect any currently attached display (window
  // parked on a since-disconnected screen). screen.* is safe here: this only
  // runs after app.whenReady().
  const stateFile = windowStateFile(app.getPath("userData"));
  const restored = loadWindowBounds(stateFile, screen.getAllDisplays());
  // P2-172: bounds feed the constructor; the maximized flag is applied in the
  // ready-to-show handler below.
  const { maximized, ...bounds } = restored;
  const win = new BrowserWindow({
    ...bounds,
    minWidth: WINDOW_MIN.width,
    minHeight: WINDOW_MIN.height,
    title: "OpenCode Remote",
    show: false,
    // P1-081: explicit so the hermetic hidden window keeps painting (real
    // frames for the gate's CDP screenshots) instead of never rendering.
    paintWhenInitiallyHidden: true,
    icon: appIcon(),
    webPreferences: {
      preload: join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      // P1-072: the Browser pane renders real pages through a sandboxed
      // <webview> (interactive scroll/click/edit) instead of screenshots.
      // contextIsolation/sandbox stay on; nodeIntegration stays off.
      webviewTag: true,
    },
  });
  win.once("ready-to-show", () => {
    // P1-081: under the hermetic e2e marker the window stays hidden — the
    // gate interacts via webContents and the operator's screen is left alone.
    if (HERMETIC_E2E) return;
    // P2-172: reopen maximized when the user quit maximized. maximize() must
    // run here, right before show(), and never in the hermetic path: Electron's
    // maximize() also SHOWS a hidden window (electron.d.ts), so calling it on
    // construction would both break the hermetic guarantee and flash an
    // unpainted window; before show() it opens directly at the maximized size.
    if (maximized) win.maximize();
    win.show();
  });
  // P3-053: focusing the window always clears the badge, even when the
  // renderer has not pushed its zero yet (busy frame, brief race) — matching
  // Claude Desktop, where activating the window means "seen". P2-150: Windows
  // joins in — the focus path routes through badgePlan too, so the taskbar
  // overlay is cleared with null exactly like the ocr:unread zero push.
  win.on("focus", () => {
    const plan = badgePlan(process.platform, 0);
    if (plan.kind === "dock") {
      try {
        app.setBadgeCount(0);
      } catch (err) {
        logError("[desktop] focus badge clear failed:", err);
      }
      return;
    }
    if (plan.kind === "overlay") applyOverlayBadge(plan);
  });
  // P2-021: track the shell window so showMainWindow() re-shows the hidden
  // one after a close-to-tray instead of spawning duplicates.
  mainWindow = win;
  // P3-008: persist bounds on "close" — it fires both on quit (app.quit()
  // closes every window) and when a previously hidden window is destroyed.
  // Failures are log-only and must never block quitting.
  // P2-021 close-to-tray: a plain close (red button, Alt+F4) hides the window
  // instead of destroying it, keeping the daemon sidecar and the tray alive.
  // A real quit (tray Quit, menu Quit — flagged via before-quit/will-quit)
  // still closes for real, so the sidecar cleanup in will-quit keeps running.
  win.on("close", (event) => {
    // P2-172: getNormalBounds (not getBounds) — a maximized window's getBounds
    // is the full work area, which would reopen as a fake-maximized window
    // nobody could restore. The normal rect plus the live isMaximized() flag
    // restore both states faithfully.
    saveWindowBounds(stateFile, { ...win.getNormalBounds(), maximized: win.isMaximized() });
    if (!quitting) {
      event.preventDefault();
      win.hide();
      // P2-152: one-time "still running" hint — only on the close-to-tray
      // branch, never on a real quit. Best-effort, after the hide.
      maybeShowCloseHint();
    }
  });
  win.on("closed", () => {
    if (mainWindow === win) mainWindow = null;
  });
  // Open external links (docs, GitHub) in the browser, never in-app.
  // P2-178: only http/https/mailto may reach the OS — the decision reason is
  // scheme-safe to log, the raw URL (conversation content) never is.
  win.webContents.setWindowOpenHandler(({ url }) => {
    const decision = externalOpenDecision(url);
    if (decision.allow) {
      void shell.openExternal(decision.href);
    } else {
      logError(`[desktop] external open refused (reason=${decision.reason})`);
    }
    return { action: "deny" };
  });
  // P3-011: a dead renderer used to leave a white, unrecoverable window.
  // Log the crash reason and reload the page (bounded by the shared budget).
  // P1-050: non-clean exits also land a crash report file in the shared
  // client-logs folder before the (possibly successful) in-place recovery.
  win.webContents.on("render-process-gone", (_event, details) => {
    if (details && details.reason !== "clean-exit") {
      reportCrash("renderer", `reason=${details.reason} exitCode=${details.exitCode}`);
    }
    onRendererGone(win, details, rendererReloadGuard, log, logError);
  });
  // A stray OS file-drop or rogue link must never navigate the window away
  // from the app shell (the renderer's own drag&drop handler is the supported
  // path; this is the last line of defense). In-app reloads stay allowed.
  win.webContents.on("will-navigate", (event, url) => {
    if (url !== win.webContents.getURL()) event.preventDefault();
  });
  loadUi(win);
  return win;
}

function loadUi(win: BrowserWindow): void {
  // Dev override: OCR_WEB_URL=http://localhost:5173 npm start
  const devUrl = process.env.OCR_WEB_URL;
  if (devUrl) {
    void win.loadURL(devUrl);
    return;
  }
  const html = webDistIndex();
  if (html) {
    void win.loadFile(html);
  } else {
    void win.loadURL(
      "data:text/html," +
        encodeURIComponent(
          `<body style="font-family:-apple-system,sans-serif;background:#111;color:#eee;display:grid;place-items:center;height:100dvh;margin:0"><div style="text-align:center"><p style="font-size:15px">OpenCode Remote — web UI not found.</p><p style="opacity:.7;font-size:13px">Run <code style="background:#333;padding:2px 6px;border-radius:4px">npm run build --workspace @ocr/web</code> first.</p></div></body>`,
        ),
    );
  }
}

function webDistIndex(): string | null {
  if (app.isPackaged) {
    const packaged = join(process.resourcesPath ?? "", "web-dist", "index.html");
    return existsSync(packaged) ? packaged : null;
  }
  // Unpackaged dev run: repo layout apps/desktop → apps/web/dist
  const candidate = join(app.getAppPath(), "..", "web", "dist", "index.html");
  return existsSync(candidate) ? candidate : null;
}

function showMainWindow(): void {
  // P1-081: no-op in hermetic e2e runs — gates the second-instance (:158) and
  // activate (:430) paths plus the tray, so a test run never surfaces a window.
  if (HERMETIC_E2E) return;
  if (!mainWindow || mainWindow.isDestroyed()) mainWindow = createWindow();
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.show();
  mainWindow.focus();
}

// P1-046: Go-menu accelerators. Each item broadcasts its action id to every
// window on "ocr:menu-action"; the renderer routes it through the view
// reducer (the same ids the web keydown fallback dispatches).
function sendMenuAction(id: string): void {
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) win.webContents.send("ocr:menu-action", id);
  }
}

// P2-176: the menu lives as pure data in menu.ts (unit-tested, no electron
// imports) and is translated here with no other logic — no labels, ids or
// accelerators are written inline anymore. The go-* ids, renderer actions and
// accelerators are byte-a-byte the P1-046 contract, so sendMenuAction keeps
// receiving exactly the same identifiers.

// P2-176: Help-submenu wiring, by id — each entry is the exact handler the
// corresponding tray item runs (no new IPC, no preload change).
const menuShellHandlers: Record<string, () => void> = {
  // Same fire-and-forget, log-only check as the tray item (P3-019).
  "help-updates": () => checkForUpdates(),
  // Same mkdir+reveal path as the tray item (P3-016).
  "help-logs": () => revealLogsFolder(),
  // Same diagnostics bundle the app:diagnostics handler serves the renderer,
  // written straight to the clipboard from the menu item.
  "help-diagnostics": () => clipboard.writeText(buildDiagnostics()),
};

function toElectronItems(items: MenuItemSpec[]): Electron.MenuItemConstructorOptions[] {
  return items.map((item) => {
    const entry: Electron.MenuItemConstructorOptions = {};
    if (item.id) entry.id = item.id;
    if (item.label !== undefined) entry.label = item.label;
    if (item.role) entry.role = item.role;
    if (item.accelerator) entry.accelerator = item.accelerator;
    if (item.enabled !== undefined) entry.enabled = item.enabled;
    if (item.type) entry.type = item.type;
    const action = item.action;
    if (action) entry.click = () => sendMenuAction(action);
    else if (item.id && menuShellHandlers[item.id]) entry.click = menuShellHandlers[item.id];
    if (item.submenu) entry.submenu = toElectronItems(item.submenu);
    return entry;
  });
}

/** The tray's update-status label, shared with the menu so both surfaces can
 * never drift apart on what the last check decided (P2-176). */
function currentUpdateLabel(): string | null {
  return lastUpdateStatus === null ? null : updateMenuLabel(lastUpdateStatus);
}

function buildMenu(): void {
  Menu.setApplicationMenu(Menu.buildFromTemplate(toElectronItems(menuSpec(process.platform, currentUpdateLabel(), updatesEnabled()))));
}

// P3-015: prefer the monochrome template asset (build/trayTemplate.png;
// nativeImage auto-loads the sibling trayTemplate@2x.png on Retina) so the
// menu-bar glyph adapts to light/dark. Same degradation as appIcon(): a
// missing/empty asset falls back to the embedded data-URL glyph. The source
// policy itself lives in tray.ts (pure, electron-free, unit-tested).
function trayImage(): Electron.NativeImage {
  const assetPath = join(app.getAppPath(), "build", "trayTemplate.png");
  const usable = existsSync(assetPath) && !nativeImage.createFromPath(assetPath).isEmpty();
  const source = trayIconSource(process.platform, assetPath, usable);
  if (source.kind === "fallback") return nativeImage.createFromDataURL(TRAY_ICON_PNG);
  const img = nativeImage.createFromPath(source.path);
  if (source.template) img.setTemplateImage(true);
  return img;
}

function buildTray(): void {
  tray = new Tray(trayImage());
  // P3-007: tooltip doubles as the sidecar health indicator; starts pessimistic
  // and is corrected by the first pairing-watcher poll (see setTrayHealthy).
  trayHealthy = false;
  tray.setToolTip(daemonTooltip(false));
  tray.setContextMenu(Menu.buildFromTemplate(trayMenuItems()));
  tray.on("click", showMainWindow);
}

// P3-019: rebuilds the context menu in place after the update status changes.
// setContextMenu swaps the items on the live Tray instance, keeping the icon
// and the click handler intact; a no-op when the tray is gone (Quit).
function refreshTrayMenu(): void {
  tray?.setContextMenu(Menu.buildFromTemplate(trayMenuItems()));
}

// P3-019/P2-176: the fire-and-forget update re-check shared by the tray item
// and the Help menu. Log-only by design and never throws — re-checks are
// safe, listeners are attached once per updater instance and deferred
// versions are not re-offered (update.ts).
function checkForUpdates(): void {
  runUpdateCheck("tray");
}

// P3-016/P2-176: the tray's "Open logs folder" handler, now shared with the
// Help menu item — the persistent desktop.log (P3-012) is useless to a lay
// user if nothing in the app points at it. This item creates the folder on
// demand and reveals it in the OS file manager. Best-effort: openLogsFolder
// resolves false instead of rejecting, so the failure stays log-only and
// can never take the shell down.
function revealLogsFolder(): void {
  const dir = logsDirPath(app.getPath("userData"));
  // P3-018: cite the concrete files in the message this item produces —
  // a user landing in the folder sees which file holds what (the shell
  // log vs. the daemon sidecar's stdout/stderr JSONL).
  log("[desktop] logs folder: desktop.log (shell), daemon-sidecar.log (daemon sidecar stdout/stderr)");
  void openLogsFolder(dir, {
    mkdir: (d, opts) => mkdirSync(d, opts),
    openPath: (p) => shell.openPath(p),
  }).then((ok) => {
    if (!ok) logError("[desktop] open logs folder failed:", dir);
  });
}

function trayMenuItems(): Electron.MenuItemConstructorOptions[] {
  const items: Electron.MenuItemConstructorOptions[] = [
    { label: "Open OpenCode Remote", click: showMainWindow },
  ];
  // P3-019/P1-050: update items exist only when a feed is configured — for an
  // unpackaged dev run without OCR_UPDATE_FEED the tray is byte-for-byte
  // identical to the pre-P3-019 menu. Packaged builds always have a feed: the
  // daemon's loopback updates folder (updatesEnabled()).
  if (updatesEnabled()) {
    const statusLabel = currentUpdateLabel();
    if (statusLabel) {
      // Informational-only state line; the install itself needs the consent
      // dialog (updateDialogSinks), never a tray mis-click.
      items.push({ label: statusLabel, enabled: false });
    }
    items.push({
      label: "Check for updates",
      click: checkForUpdates,
    });
  }
  items.push({
    // P3-017: always-present one-click recovery for a sidecar whose respawn
    // budget is exhausted (P2-017) or an adopted daemon gone unstable.
    label: "Restart daemon",
    click: () => {
      // Best-effort: restartDaemon is try/caught and log-only; the extra
      // .catch keeps any unexpected rejection away from the shell.
      void restartDaemon().catch((err) => logError("[desktop] tray restart daemon failed:", err));
    },
  });
  // Login autostart is a no-op outside macOS/Windows — hide it elsewhere.
  if (loginItemSupported(process.platform)) {
    items.push({
      label: "Start at login",
      type: "checkbox",
      checked: app.getLoginItemSettings().openAtLogin,
      // For checkbox items `item.checked` is the state after the user toggled,
      // which is exactly what setLoginItemSettings must persist (macOS launch
      // services / Windows registry) — so the choice survives app restarts.
      click: (item) => app.setLoginItemSettings({ openAtLogin: item.checked }),
    });
  }
  // P3-016: the persistent desktop.log (P3-012) is useless to a lay user if
  // nothing in the app points at it — this item creates the folder on demand
  // and reveals it in the OS file manager (the same handler the Help menu's
  // "Abrir pasta de logs" item runs since P2-176). Best-effort: openLogsFolder
  // resolves false instead of rejecting, so the failure stays log-only and
  // can never take the shell down.
  items.push({
    label: "Open logs folder",
    click: revealLogsFolder,
  });
  items.push(
    { type: "separator" },
    {
      label: "Quit",
      click: () => {
        // P2-021: real quit — flag before app.quit() so the close handler
        // doesn't hide; will-quit then stops the daemon sidecar with cleanup.
        quitting = true;
        tray = null;
        app.quit();
      },
    },
  );
  return items;
}
