import { app, BrowserWindow, ipcMain, Menu, nativeImage, Notification, screen, Tray, shell } from "electron";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import QRCode from "qrcode";
import {
  DAEMON_METRICS_PORT,
  getPairUrl,
  isDaemonDown,
  readApiToken,
  restartDaemon,
  startDaemonSidecar,
  stopDaemonSidecar,
  waitForDaemonHealth,
} from "./daemon";
import { initDesktopLog, log, logError } from "./desktop-log";
import { phonePaired, type PairingState } from "./pairing";
import { daemonNotify, NOTIFY_BACK_BODY, NOTIFY_DOWN_BODY, NOTIFY_TITLE, type DaemonHealth } from "./notify";
import { deepLinkFromArgv, parseDeepLink } from "./deeplink";
import { daemonTooltip, loginItemSupported, trayIconSource } from "./tray";
import { checkForUpdatesOnBoot, feedUrlFromEnv, updateMenuLabel, type UpdateStatus } from "./update";
import { loadWindowBounds, saveWindowBounds, WINDOW_MIN, windowStateFile } from "./window-state";
import { installFatalErrorHandlers, onRendererGone, ReloadGuard } from "./crash";

// Tray fallback glyph (P3-009): since P3-015 the tray prefers the monochrome
// template asset build/trayTemplate.png (generated by scripts/make-icon.mjs),
// which macOS recolors to match the light/dark menu bar. This data-URL stays
// as the degradation path when that asset is missing or empty.
const TRAY_ICON_PNG =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAPUlEQVR4nGNgoAWQkJD+jw2TrZEog5AVKB2Nw4rxGkJIM7ohZGnGacioAVQwgOJopEpCojgpE2MQQY3kAABalSlohfDTkQAAAABJRU5ErkJggg==";

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let daemonStopped = false;
// P2-021: set by every real quit path (tray Quit, before-quit, will-quit) so
// the window's close handler can tell "user closed the window" apart from
// "app is shutting down" — close-to-tray on every platform.
let quitting = false;
// P3-019: latest update-check decision (null = no check resolved yet). Kept in
// the main process and surfaced only through the tray menu — no new IPC.
let lastUpdateStatus: UpdateStatus | null = null;

// P3-012: file logging installed before anything can log — console.* in the
// packaged app is invisible to the stage-5 user (no terminal), so every
// main-process line now also lands in userData/logs/desktop.log (~1MB cap,
// one rotated file kept). Write failures are log-only and never throw.
initDesktopLog(app.getPath("userData"));
// P3-011: a main-process exception used to crash Electron without will-quit,
// killing the daemon sidecar with no cleanup. Installed before anything can
// throw, so even boot-time failures quit through the graceful path. Fatal
// errors route through the file logger too (sink injection).
installFatalErrorHandlers(app, { error: logError });
// P3-011: shared crash-recovery budget — max 3 renderer reloads per 60s.
const rendererReloadGuard = new ReloadGuard();

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
} else {
  // P3-014: OS-level registration for opencode-remote:// pair links. Packaged
  // builds only — a dev run must never steal the OS handler — and only on the
  // platforms that support the flow (macOS open-url, Windows second-instance
  // argv). Registration covers the packaged app alone; electron-builder
  // declares the scheme in the bundle (protocols: in electron-builder.yml).
  if (app.isPackaged && (process.platform === "darwin" || process.platform === "win32")) {
    app.setAsDefaultProtocolClient("opencode-remote");
  }
  // macOS: Finder/LaunchServices hands the URL over before ready on a cold
  // start — register early so the very first launch already pairs.
  app.on("open-url", (event, url) => {
    event.preventDefault();
    handleDeepLink(url);
  });
  app.on("second-instance", (_event, argv) => {
    showMainWindow();
    // Windows: the OS spawns a second process whose argv carries the URL;
    // the single-instance winner receives it here.
    handleDeepLink(deepLinkFromArgv(argv));
  });
  app
    .whenReady()
    .then(() => onReady())
    .catch((err) => {
      logError("[desktop] startup failed:", err);
      app.quit();
    });
}

async function onReady(): Promise<void> {
  buildMenu();
  buildTray();

  // P3-009: real app icon (build/icon.png, generated by scripts/make-icon.mjs)
  // for the macOS dock — on Windows/Linux the BrowserWindow icon below does
  // the job, on macOS the window icon is ignored and the dock is the surface
  // that matters. Missing/empty asset degrades to Electron defaults.
  const icon = appIcon();
  if (icon && process.platform === "darwin" && app.dock) app.dock.setIcon(icon);
  app.setAboutPanelOptions({
    applicationName: "OpenCode Remote",
    applicationVersion: app.getVersion(),
  });

  // P2-012: staged update feed spike. Runs once at boot, fire-and-forget (a
  // slow or dead feed must never delay window creation) and only acts when
  // OCR_UPDATE_FEED is set — otherwise it is a silent no-op. All failures are
  // log-only (see src/update.ts). P3-019: the resolved status is stored and
  // mirrored into the tray menu, so a lay user can see an available update.
  void checkForUpdatesOnBoot()
    .then((status) => {
      lastUpdateStatus = status;
      refreshTrayMenu();
    })
    .catch((err) => logError("[desktop] boot update check failed:", err));

  ipcMain.handle("app:version", () => app.getVersion());
  // P2-011: narrow HTTP bridge to the local daemon's /api/browse surface so
  // the renderer can drive the host browser without ever seeing the api token
  // (the 0600 state file stays in this main process). Loopback only, browse
  // routes only — the token never leaves this process.
  ipcMain.handle("app:daemonBrowse", async (_e, req: { path?: string; method?: string; body?: unknown }) => {
    if (!req || typeof req.path !== "string") return null;
    const method = req.method === "POST" ? "POST" : "GET";
    // Anchored, URL-parsed allowlist: `new URL` normalizes ../ traversal into
    // the pathname, so only genuine /api/browse[/action] paths can pass. The
    // outbound URL is rebuilt from the parsed components — the raw renderer
    // string is never forwarded.
    const u = new URL(req.path, "http://127.0.0.1");
    if (!/^\/api\/browse(\/[a-z]+)?$/.test(u.pathname)) return null;
    try {
      const stateFile = join(homedir(), ".opencode-remote", "daemon.json");
      const token = (JSON.parse(readFileSync(stateFile, "utf8")) as { apiToken?: string }).apiToken;
      if (!token) return null;
      const res = await fetch(`http://127.0.0.1:${DAEMON_METRICS_PORT}${u.pathname}${u.search}`, {
        method,
        headers: { authorization: `Bearer ${token}` },
        body: method === "POST" ? JSON.stringify(req.body ?? {}) : undefined,
        signal: AbortSignal.timeout(45_000),
      });
      // defense in depth: the daemon bounds its payloads, but never trust that
      // blindly — a screenshot is a few MB, so 32 MB is a generous ceiling
      const raw = await res.arrayBuffer();
      if (raw.byteLength > 32 * 1024 * 1024) return null;
      return { status: res.status, contentType: res.headers.get("content-type") ?? "", body: Buffer.from(raw).toString("base64") };
    } catch (err) {
      logError("[desktop] daemonBrowse failed:", err);
      return null;
    }
  });
  // Boot pairing URI captured from the daemon sidecar's stdout (null when the
  // daemon was reused or hasn't printed it yet) — lets the renderer auto-pair.
  ipcMain.handle("app:pairUrl", () => getPairUrl());
  // P3-014: late pull for opencode-remote:// pair links. A renderer mounting
  // after the OS already handed over the URL (cold start via open-url) reads
  // the cached value here; consumed once so a stale link can't loop around.
  ipcMain.handle("app:deepLink", () => {
    const uri = lastDeepLink;
    lastDeepLink = null;
    return uri;
  });
  // P2-007: first-run pairing state for the renderer's QR overlay. The main
  // process polls the daemon (see startPairingWatcher) and caches the result;
  // the sandboxed renderer only ever sees this derived state — never the
  // apiToken, allowlist file or raw HTTP responses.
  ipcMain.handle("app:pairingState", () => pairingState);
  // Host self-approval: the desktop shell runs on the same machine that owns
  // daemon.json, so it may add its own client identity to the allowlist. The
  // daemon re-reads the allowlist file on every handshake (fresh read), so
  // this takes effect on the next connect without a daemon restart.
  ipcMain.handle("app:approveClient", (_e, pub: string) => {
    if (typeof pub !== "string" || pub.length < 40 || !/^[A-Za-z0-9+/=]+$/.test(pub)) {
      return false;
    }
    try {
      const file = join(homedir(), ".opencode-remote", "daemon.json");
      const raw = JSON.parse(readFileSync(file, "utf8")) as {
        clients?: { pub: string; label?: string; addedAt: string }[];
      };
      raw.clients ??= [];
      if (raw.clients.some((c) => c.pub === pub)) return true;
      raw.clients.push({ pub, label: "desktop-host", addedAt: new Date().toISOString() });
      writeFileSync(file, JSON.stringify(raw, null, 2), { mode: 0o600 });
      return true;
    } catch (err) {
      logError("[desktop] approveClient failed:", err);
      return false;
    }
  });

  // Sidecar: boot a local daemon (unless one is already healthy), wait for
  // /api/health before showing the UI. On timeout we still show the UI —
  // it renders its own disconnected state. waitForDaemonHealth reuses the
  // token captured by startDaemonSidecar and aborts early if the child died.
  const daemonReady = await startDaemonSidecar(
    app.getAppPath(),
    app.isPackaged ? process.resourcesPath : undefined,
  );
  if (!daemonReady || !(await waitForDaemonHealth())) {
    logError(`[desktop] daemon health not confirmed on :${DAEMON_METRICS_PORT} — continuing`);
  }

  createWindow();
  startPairingWatcher();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
    else showMainWindow();
  });
  app.on("window-all-closed", () => {
    // P2-021: with close-to-tray the window is hidden on close, so this only
    // fires when windows are really gone (win.destroy, crash cleanup).
    // Keep the tray alive on macOS (convention); quit elsewhere.
    if (process.platform !== "darwin") app.quit();
  });
  app.on("before-quit", () => {
    // Every app.quit() path (tray Quit, menu role, window-all-closed) is a
    // real quit: the close handler must let the window die instead of hiding.
    quitting = true;
  });
  app.on("will-quit", (event) => {
    // Encerra o daemon que subimos antes de sair (idempotente).
    if (daemonStopped) return;
    event.preventDefault();
    quitting = true;
    if (pairingTimer) clearInterval(pairingTimer);
    void stopDaemonSidecar().then(() => {
      daemonStopped = true;
      app.quit();
    });
  });
}

// --- opencode-remote:// deep links (P3-014) ----------------------------------
// The OS hands the shell a raw URL (macOS open-url, Windows second-instance
// argv) whenever an install/invite page opens the app. Validation is pure
// (src/deeplink.ts): only a well-formed pair URI passes. A valid link is
// cached for the renderer's late pull (app:deepLink) and pushed to any live
// window; the renderer routes it through the same parsePairingUri path as
// paste-pairing — no new crypto.

let lastDeepLink: string | null = null;

function handleDeepLink(raw: unknown): void {
  const uri = parseDeepLink(raw);
  if (!uri) return;
  // Logged without the URI: it carries the room's pairing key material and
  // the desktop.log lives on disk unencrypted.
  log("[desktop] deep link accepted (opencode-remote://pair)");
  lastDeepLink = uri;
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) win.webContents.send("ocr:deep-link", uri);
  }
}

// --- first-run pairing watcher (P2-007) --------------------------------------
// After daemon health OK, poll the loopback API every 3s: while no phone is
// paired, fetch the boot pairing URI, render it as a PNG data-URL and hand the
// whole state to the renderer, which draws the QR overlay. As soon as the
// allowlist holds a non-host device (the phone scanned the QR), the overlay
// leaves and the chat shows. Read-only end to end: the allowlist itself is
// only ever read, never written here.

const PAIRING_POLL_MS = 3_000;
const PROBE_TIMEOUT_MS = 2_000;

let pairingState: PairingState | null = null;
let pairingTimer: NodeJS.Timeout | null = null;

/** Placeholder state while the sidecar is down for good (P2-017): no QR (the
 * old room/keys are dead with the daemon), just the "daemon down" flag. */
function daemonDownState(): PairingState {
  return { uri: null, qrDataUrl: null, devices: 0, phonePaired: false, daemonDown: true };
}

function setPairingState(next: PairingState | null): void {
  const changed = JSON.stringify(next) !== JSON.stringify(pairingState);
  pairingState = next;
  // Push so the overlay reacts within one poll; the renderer also pulls
  // (invoke) on mount — a fresh window never waits for a change. Broadcast to
  // every window: createWindow() doesn't track a single mainWindow handle.
  if (changed) {
    for (const win of BrowserWindow.getAllWindows()) {
      if (!win.isDestroyed()) win.webContents.send("ocr:pairing-state", pairingState);
    }
  }
}

// --- tray tooltip as sidecar health indicator (P3-007) -----------------------
// Fed by the pairing watcher's 3s poll below: the last authenticated request
// against the daemon decides ok/down. Deduplicated so the tooltip is only
// rewritten on actual transitions.

let trayHealthy: boolean | null = null;

function setTrayHealthy(healthy: boolean): void {
  if (trayHealthy === healthy) return;
  trayHealthy = healthy;
  tray?.setToolTip(daemonTooltip(healthy));
  log(`[desktop] tray tooltip: ${daemonTooltip(healthy)}`);
}

// --- native daemon notifications (P3-013) -------------------------------------
// Fed by the same poll as the tray tooltip: when the sidecar's respawn budget
// is exhausted (isDaemonDown() true) the window may be closed to the tray, and
// a tray tooltip alone never reaches a non-technical user — so each real
// transition fires a native notification instead. Decision logic is pure
// (src/notify.ts) and tested in scripts/unit.test.ts.

let daemonHealthObserved: DaemonHealth | null = null;

function observeDaemonHealth(down: boolean): void {
  const next: DaemonHealth = down ? "down" : "healthy";
  const decision = daemonNotify(daemonHealthObserved, next);
  daemonHealthObserved = next;
  if (decision.notify === "none") return;
  // Best-effort only: an unsupporting platform, a full disk or a denied
  // permission must never take the shell down — the poll continues regardless.
  try {
    if (!Notification.isSupported()) return;
    const body = decision.notify === "down" ? NOTIFY_DOWN_BODY : NOTIFY_BACK_BODY;
    new Notification({ title: NOTIFY_TITLE, body, silent: false }).show();
    log(`[desktop] notification: ${body}`);
  } catch (err) {
    logError("[desktop] daemon notification failed:", err);
  }
}

async function refreshPairingState(): Promise<void> {
  const token = readApiToken();
  if (!token) {
    // Cannot prove health without the token — report down until proven ok.
    setTrayHealthy(false);
    observeDaemonHealth(isDaemonDown());
    setPairingState(isDaemonDown() ? daemonDownState() : null);
    return;
  }
  const base = `http://127.0.0.1:${DAEMON_METRICS_PORT}`;
  const headers = { authorization: `Bearer ${token}` };
  try {
    const devRes = await fetch(`${base}/__ocr/devices`, { headers, signal: AbortSignal.timeout(PROBE_TIMEOUT_MS) });
    if (!devRes.ok) throw new Error(`devices ${devRes.status}`);
    const { devices } = (await devRes.json()) as { devices?: { pub: string; label?: string }[] };
    if (!Array.isArray(devices)) throw new Error("malformed devices payload");
    setTrayHealthy(true);
    // The daemon answers (adopted or sidecar) — control is back.
    observeDaemonHealth(false);

    const paired = phonePaired(devices);
    let uri = pairingState?.uri ?? null;
    let qrDataUrl = pairingState?.qrDataUrl ?? null;
    if (!paired && !uri) {
      // Only fetch/refresh while the overlay may still be needed; once a phone
      // is paired the QR is dead weight.
      const uriRes = await fetch(`${base}/__ocr/pairing-uri`, {
        headers,
        signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
      });
      if (!uriRes.ok) throw new Error(`pairing-uri ${uriRes.status}`);
      uri = ((await uriRes.json()) as { uri?: string }).uri ?? null;
      if (uri) qrDataUrl = await QRCode.toDataURL(uri, { margin: 1, width: 480 });
    }
    setPairingState({ uri, qrDataUrl, devices: devices.length, phonePaired: paired });
  } catch (err) {
    // Daemon down, token rotated or state file wiped: drop the cached state so
    // a stale QR (old room/keys) is never shown. The next healthy tick
    // rebuilds everything from scratch. When the sidecar exhausted its
    // respawn budget (P2-017), tell the renderer instead of staying silent.
    logError(`[desktop] pairing poll failed: ${err instanceof Error ? err.message : err}`);
    setTrayHealthy(false);
    observeDaemonHealth(isDaemonDown());
    if (isDaemonDown()) {
      setPairingState(daemonDownState());
    } else {
      setPairingState(null);
    }
  }
}

function startPairingWatcher(): void {
  if (pairingTimer) return;
  void refreshPairingState();
  pairingTimer = setInterval(() => void refreshPairingState(), PAIRING_POLL_MS);
}

// P3-009: the packaged app ships build/icon.png inside the asar (files list in
// electron-builder.yml) and dev runs resolve it next to the sources; Electron
// reads images through asar transparently.
function appIcon(): Electron.NativeImage | undefined {
  const path = join(app.getAppPath(), "build", "icon.png");
  if (!existsSync(path)) return undefined;
  const img = nativeImage.createFromPath(path);
  return img.isEmpty() ? undefined : img;
}

function createWindow(): BrowserWindow {
  // P3-008: restore the last window bounds. loadWindowBounds degrades to the
  // 1280x820 default on a missing/corrupted file, and sanitizeWindowBounds
  // drops bounds that don't intersect any currently attached display (window
  // parked on a since-disconnected screen). screen.* is safe here: this only
  // runs after app.whenReady().
  const stateFile = windowStateFile(app.getPath("userData"));
  const bounds = loadWindowBounds(stateFile, screen.getAllDisplays());
  const win = new BrowserWindow({
    ...bounds,
    minWidth: WINDOW_MIN.width,
    minHeight: WINDOW_MIN.height,
    title: "OpenCode Remote",
    show: false,
    icon: appIcon(),
    webPreferences: {
      preload: join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });
  win.once("ready-to-show", () => win.show());
  // P2-021: track the shell window so showMainWindow() re-shows the hidden
  // one after a close-to-tray instead of spawning duplicates.
  mainWindow = win;
  // P3-008: persist bounds on "close" — it fires both on quit (app.quit()
  // closes every window) and when a previously hidden window is destroyed.
  // Failures are log-only and must never block quitting.
  // P2-021 close-to-tray: a plain close (red button, Alt+F4) hides the window
  // instead of destroying it, keeping the daemon sidecar and the tray alive.
  // A real quit (tray Quit, menu Quit — flagged via before-quit/will-quit)
  // still closes for real, so the sidecar cleanup in will-quit keeps running.
  win.on("close", (event) => {
    saveWindowBounds(stateFile, win.getBounds());
    if (!quitting) {
      event.preventDefault();
      win.hide();
    }
  });
  win.on("closed", () => {
    if (mainWindow === win) mainWindow = null;
  });
  // Open external links (docs, GitHub) in the browser, never in-app.
  win.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: "deny" };
  });
  // P3-011: a dead renderer used to leave a white, unrecoverable window.
  // Log the crash reason and reload the page (bounded by the shared budget).
  win.webContents.on("render-process-gone", (_event, details) => {
    onRendererGone(win, details, rendererReloadGuard, log, logError);
  });
  loadUi(win);
  return win;
}

function loadUi(win: BrowserWindow): void {
  // Dev override: OCR_WEB_URL=http://localhost:5173 npm start
  const devUrl = process.env.OCR_WEB_URL;
  if (devUrl) {
    void win.loadURL(devUrl);
    return;
  }
  const html = webDistIndex();
  if (html) {
    void win.loadFile(html);
  } else {
    void win.loadURL(
      "data:text/html," +
        encodeURIComponent(
          `<body style="font-family:-apple-system,sans-serif;background:#111;color:#eee;display:grid;place-items:center;height:100dvh;margin:0"><div style="text-align:center"><p style="font-size:15px">OpenCode Remote — web UI not found.</p><p style="opacity:.7;font-size:13px">Run <code style="background:#333;padding:2px 6px;border-radius:4px">npm run build --workspace @ocr/web</code> first.</p></div></body>`,
        ),
    );
  }
}

function webDistIndex(): string | null {
  if (app.isPackaged) {
    const packaged = join(process.resourcesPath ?? "", "web-dist", "index.html");
    return existsSync(packaged) ? packaged : null;
  }
  // Unpackaged dev run: repo layout apps/desktop → apps/web/dist
  const candidate = join(app.getAppPath(), "..", "web", "dist", "index.html");
  return existsSync(candidate) ? candidate : null;
}

function showMainWindow(): void {
  if (!mainWindow || mainWindow.isDestroyed()) mainWindow = createWindow();
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.show();
  mainWindow.focus();
}

function buildMenu(): void {
  const template: Electron.MenuItemConstructorOptions[] = [
    ...(process.platform === "darwin"
      ? [
          {
            label: app.name,
            submenu: [
              { role: "about" as const },
              { type: "separator" as const },
              { role: "hide" as const },
              { role: "quit" as const, label: "Quit OpenCode Remote" },
            ],
          },
        ]
      : []),
    { role: "editMenu" },
    {
      label: "View",
      submenu: [
        { role: "reload" },
        { role: "forceReload" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "toggleDevTools" },
      ],
    },
    { role: "windowMenu" },
  ];
  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

// P3-015: prefer the monochrome template asset (build/trayTemplate.png;
// nativeImage auto-loads the sibling trayTemplate@2x.png on Retina) so the
// menu-bar glyph adapts to light/dark. Same degradation as appIcon(): a
// missing/empty asset falls back to the embedded data-URL glyph. The source
// policy itself lives in tray.ts (pure, electron-free, unit-tested).
function trayImage(): Electron.NativeImage {
  const assetPath = join(app.getAppPath(), "build", "trayTemplate.png");
  const usable = existsSync(assetPath) && !nativeImage.createFromPath(assetPath).isEmpty();
  const source = trayIconSource(process.platform, assetPath, usable);
  if (source.kind === "fallback") return nativeImage.createFromDataURL(TRAY_ICON_PNG);
  const img = nativeImage.createFromPath(source.path);
  if (source.template) img.setTemplateImage(true);
  return img;
}

function buildTray(): void {
  tray = new Tray(trayImage());
  // P3-007: tooltip doubles as the sidecar health indicator; starts pessimistic
  // and is corrected by the first pairing-watcher poll (see setTrayHealthy).
  trayHealthy = false;
  tray.setToolTip(daemonTooltip(false));
  tray.setContextMenu(Menu.buildFromTemplate(trayMenuItems()));
  tray.on("click", showMainWindow);
}

// P3-019: rebuilds the context menu in place after the update status changes.
// setContextMenu swaps the items on the live Tray instance, keeping the icon
// and the click handler intact; a no-op when the tray is gone (Quit).
function refreshTrayMenu(): void {
  tray?.setContextMenu(Menu.buildFromTemplate(trayMenuItems()));
}

function trayMenuItems(): Electron.MenuItemConstructorOptions[] {
  const items: Electron.MenuItemConstructorOptions[] = [
    { label: "Open OpenCode Remote", click: showMainWindow },
  ];
  // P3-019: update items exist only when a feed is configured — without
  // OCR_UPDATE_FEED the tray is byte-for-byte identical to the pre-P3-019 menu.
  if (feedUrlFromEnv() != null) {
    const statusLabel = lastUpdateStatus === null ? null : updateMenuLabel(lastUpdateStatus);
    if (statusLabel) {
      // Informational-only: installing still happens on the next restart.
      items.push({ label: statusLabel, enabled: false });
    }
    items.push({
      label: "Check for updates",
      click: () => {
        // Same fire-and-forget shape as "Restart daemon" (P3-017): the check
        // is log-only and never throws by design, but the extra .catch keeps
        // an unexpected rejection away from the shell. The resolved status
        // re-renders the menu so the new state becomes immediately visible.
        void checkForUpdatesOnBoot()
          .then((status) => {
            lastUpdateStatus = status;
            refreshTrayMenu();
          })
          .catch((err) => logError("[desktop] tray update check failed:", err));
      },
    });
  }
  items.push({
    // P3-017: always-present one-click recovery for a sidecar whose respawn
    // budget is exhausted (P2-017) or an adopted daemon gone unstable.
    label: "Restart daemon",
    click: () => {
      // Best-effort: restartDaemon is try/caught and log-only; the extra
      // .catch keeps any unexpected rejection away from the shell.
      void restartDaemon().catch((err) => logError("[desktop] tray restart daemon failed:", err));
    },
  });
  // Login autostart is a no-op outside macOS/Windows — hide it elsewhere.
  if (loginItemSupported(process.platform)) {
    items.push({
      label: "Start at login",
      type: "checkbox",
      checked: app.getLoginItemSettings().openAtLogin,
      // For checkbox items `item.checked` is the state after the user toggled,
      // which is exactly what setLoginItemSettings must persist (macOS launch
      // services / Windows registry) — so the choice survives app restarts.
      click: (item) => app.setLoginItemSettings({ openAtLogin: item.checked }),
    });
  }
  items.push(
    { type: "separator" },
    {
      label: "Quit",
      click: () => {
        // P2-021: real quit — flag before app.quit() so the close handler
        // doesn't hide; will-quit then stops the daemon sidecar with cleanup.
        quitting = true;
        tray = null;
        app.quit();
      },
    },
  );
  return items;
}
