// Pure decision logic for the desktop tray (P3-007). Kept free of electron
// imports so scripts/unit.test.ts can exercise it (same pattern as pairing.ts).

/** Tooltip shown by the tray: doubles as the sidecar health indicator, kept in
 * sync by the 3s pairing-watcher poll in main.ts. */
export function daemonTooltip(healthy: boolean): string {
  return healthy ? "OpenCode Remote — daemon ok" : "OpenCode Remote — daemon down";
}

/** app.setLoginItemSettings/getLoginItemSettings are no-ops outside macOS and
 * Windows (Electron docs), so the "Start at login" item is shown only there. */
export function loginItemSupported(platform: string): boolean {
  return platform === "darwin" || platform === "win32";
}

/** Which image source buildTray() hands to `new Tray(...)`. */
export interface TrayIconSource {
  /** "asset" = menu-bar PNG generated by make-icon.mjs; "fallback" = the
   * embedded data-URL glyph in main.ts (same degradation as appIcon()). */
  kind: "asset" | "fallback";
  /** Absolute asset path when kind === "asset"; empty string on fallback. */
  path: string;
  /** Template images render as an alpha mask macOS recolors for light/dark
   * menu bars; only the real asset is a template, never the fallback. */
  template: boolean;
}

/** P3-015: pure decision of which tray icon source to use, kept free of
 * electron like the rest of this module so the unit battery can exercise it.
 * `assetUsable` folds the main.ts runtime checks (existsSync + image not
 * empty) into one fact; this function owns the path/platform policy. */
export function trayIconSource(platform: string, assetPath: string, assetUsable: boolean): TrayIconSource {
  return assetUsable
    ? { kind: "asset", path: assetPath, template: platform === "darwin" }
    : { kind: "fallback", path: "", template: false };
}
