/**
 * P2-255 — the Homebrew cask contract for the release workflow.
 *
 * docs/VISION.md stage 5 leaves a Mac user with nothing but loose DMGs on a
 * releases page: the winget manifests (P2-245) gave Windows a package-manager
 * install path, but the only Homebrew artifact in the pipeline is the source
 * formula (Formula/opencode-remote.rb), which installs the code tarball, not
 * the app. This module is the deterministic half of the same fix for macOS
 * (the release.yml step wires the I/O):
 *
 *   - buildCaskManifest(...) → the cask document for the release as a file
 *     name plus its text, generated from the documented cask identifier, the
 *     release version, the two published DMG URLs (Apple Silicon and Intel)
 *     and the two sha256 digests the checksum job already computed, one
 *     architecture block each. Fail-closed: an empty or malformed version, a
 *     non-https URL, a URL outside this project's own releases page and a
 *     hash that is not exactly 64 hex digits are refused, never published.
 *   - caskProblems(...)      → everything wrong with a generated cask against
 *     the release facts, in the same plain string[] format as
 *     scripts/wingetmanifest.ts and scripts/release-checksums.ts: one
 *     problem per cause, rules applied in a fixed order with no
 *     short-circuit, every text one sentence naming what to do.
 *
 * Pure by construction: no fs, no child process, no network — the caller
 * reads the real-world inputs (the tag, the published asset list, the
 * checksums.txt text) and injects them, so the unit battery can pin every
 * branch with synthetic fixtures and the real-repo assertion in
 * scripts/unit.test.ts pins the workflow wiring.
 */

/** The cask token documented in README/README.pt-BR/docs. */
export const CASK_IDENTIFIER = "opencode-remote";

/** The flat file name the generated cask is published under in every release. */
export const CASK_FILE_NAME = `${CASK_IDENTIFIER}-cask.rb`;

/** The only place a DMG URL may live: this project's own releases. */
export const CASK_RELEASES_BASE =
  "https://github.com/caiovicentino/opencode-remote/releases/download/";

/** The generated cask: its flat file name and its full text. */
export interface CaskManifest {
  fileName: string;
  text: string;
}

const VERSION_RE = /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;
const SHA256_RE = /^[0-9a-fA-F]{64}$/;

function refuse(ok: boolean, message: string): void {
  if (!ok) throw new Error(`cask-manifest: ${message}`);
}

/** Validate one DMG address: a URL at all, https, this project's releases. */
function refuseBadUrl(url: string, what: string): void {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    throw new Error(`cask-manifest: the ${what} address is not a URL at all`);
  }
  refuse(
    parsed.protocol === "https:",
    `the ${what} address is not https — a cask may only point at an encrypted download`,
  );
  refuse(
    parsed.href.startsWith(CASK_RELEASES_BASE),
    `the ${what} address does not point at this project's own releases page — a cask must never redirect the install elsewhere`,
  );
}

/**
 * The cask document for a release: both architecture blocks (Apple Silicon
 * `on_arm`, Intel `on_intel`), each carrying its own DMG address and sha256.
 * Throws on any input a published cask must never carry: an empty or
 * non-semver version, a non-https DMG address, an address outside the
 * project's own releases page, or a hash that is not exactly 64 hex digits.
 */
export function buildCaskManifest(
  version: string,
  arm64Url: string,
  x64Url: string,
  arm64Sha256: string,
  x64Sha256: string,
): CaskManifest {
  refuse(version.length > 0, "the version is empty — pass the bare semver of the release tag");
  refuse(
    VERSION_RE.test(version),
    `version "${version}" is not a semver x.y.z — derive it from the release tag`,
  );
  refuseBadUrl(arm64Url, "Apple Silicon DMG");
  refuseBadUrl(x64Url, "Intel DMG");
  refuse(
    SHA256_RE.test(arm64Sha256),
    "the Apple Silicon sha256 is not exactly 64 hex digits — pass the digest the checksum job computed",
  );
  refuse(
    SHA256_RE.test(x64Sha256),
    "the Intel sha256 is not exactly 64 hex digits — pass the digest the checksum job computed",
  );

  const text = [
    "# Homebrew cask generated by the opencode-remote release pipeline (P2-255).",
    "# Install without dragging any DMG by hand:",
    `#   brew install --cask ./${CASK_FILE_NAME}`,
    `cask "${CASK_IDENTIFIER}" do`,
    `  version "${version}"`,
    "",
    "  on_arm do",
    `    sha256 "${arm64Sha256.toLowerCase()}"`,
    `    url "${arm64Url}"`,
    "  end",
    "",
    "  on_intel do",
    `    sha256 "${x64Sha256.toLowerCase()}"`,
    `    url "${x64Url}"`,
    "  end",
    "",
    '  name "OpenCode Remote"',
    '  desc "Control opencode from your phone — E2E encrypted, blind relay"',
    '  homepage "https://github.com/caiovicentino/opencode-remote"',
    "",
    '  app "OpenCode Remote.app"',
    "end",
    "",
  ].join("\n");
  return { fileName: CASK_FILE_NAME, text };
}

/** The bare version of a release tag — the leading v is optional (P2-151). */
function bareVersion(tag: string): string {
  return tag.startsWith("v") ? tag.slice(1) : tag;
}

/** The `on_arm` / `on_intel` block of a generated cask text, or "". */
function archBlock(text: string, arch: "arm" | "intel"): string {
  const start = text.indexOf(`  on_${arch} do`);
  if (start === -1) return "";
  const end = text.indexOf("\n  end", start);
  return end === -1 ? "" : text.slice(start, end);
}

/** The `"..."` value of a `field "value"` line inside a block, or "". */
function quotedField(block: string, field: string): string {
  const line = block.split("\n").find((l) => l.trimStart().startsWith(`${field} "`));
  if (!line) return "";
  const match = line.match(new RegExp(`${field} "([^"]*)"`));
  return match ? match[1]! : "";
}

/** The release tag a download URL points into (the segment after the base). */
function urlTagSegment(url: string): string {
  try {
    const rest = new URL(url).href.slice(CASK_RELEASES_BASE.length);
    return rest.split("/")[0] ?? "";
  } catch {
    return "";
  }
}

/** The asset name a download URL points at, decoded (GitHub names may carry spaces). */
function urlAssetName(url: string): string {
  try {
    const base = new URL(url).pathname.split("/").pop() ?? "";
    try {
      return decodeURIComponent(base);
    } catch {
      return base;
    }
  } catch {
    return "";
  }
}

/** The `<hash>  <name>` line of checksums.txt for one asset, or "". */
function checksumLine(checksumsText: string, assetName: string): string {
  return checksumsText.split(/\r?\n/).find((line) => line.endsWith(`  ${assetName}`)) ?? "";
}

/**
 * Every problem with a generated cask against the release facts, all at
 * once, in the wingetProblems/release-checksums string[] format. Rules
 * applied in this fixed order, one problem per cause, no short-circuit:
 *   1. the declared version differs from the release tag;
 *   2. the Apple Silicon DMG address points at an asset absent from the
 *      release (or is unusable);
 *   3. the Intel DMG address points at an asset absent from the release
 *      (or is unusable);
 *   4. the declared Apple Silicon sha256 differs from the sum in the
 *      attached checksums.txt (or confirms nothing);
 *   5. the declared Intel sha256 differs from the sum in the attached
 *      checksums.txt (or confirms nothing);
 *   6. the Apple Silicon address points at a release other than the tag;
 *   7. the Intel address points at a release other than the tag.
 * The order is stable for the same input, and no problem text carries an
 * absolute file path or a secret.
 */
export function caskProblems(
  cask: CaskManifest,
  tag: string,
  assetNames: readonly string[],
  checksumsText: string,
): string[] {
  const problems: string[] = [];

  const declaredVersion = quotedField(cask.text, "version");
  if (declaredVersion === "") {
    problems.push(
      "cask-manifest: the cask declares no version — regenerate the cask from the release tag so Homebrew can pin the installed version",
    );
  } else if (declaredVersion !== bareVersion(tag)) {
    problems.push(
      `cask-manifest: the cask declares version ${declaredVersion} but the release tag is ${tag} — regenerate the cask from the tag before attaching it`,
    );
  }

  const urls: { label: string; arch: "arm" | "intel"; url: string }[] = (["arm", "intel"] as const)
    .map((arch) => ({
      label: arch === "arm" ? "Apple Silicon" : "Intel",
      arch,
      url: quotedField(archBlock(cask.text, arch), "url"),
    }));

  for (const { label, url } of urls) {
    const assetName = urlAssetName(url);
    if (url === "" || assetName === "") {
      problems.push(
        `cask-manifest: the cask declares no usable ${label} DMG address — regenerate the cask so its block points at the published ${label} DMG`,
      );
    } else if (!assetNames.includes(assetName)) {
      problems.push(
        `cask-manifest: the ${label} address points at asset "${assetName}" which the release does not carry — regenerate the cask after the ${label} DMG is attached`,
      );
    }
  }

  for (const { label, arch, url } of urls) {
    const block = archBlock(cask.text, arch);
    const declaredSha = quotedField(block, "sha256");
    const assetName = urlAssetName(url);
    const publishedSha =
      assetName === "" ? "" : checksumLine(checksumsText, assetName).split("  ")[0] ?? "";
    if (declaredSha === "") {
      problems.push(
        `cask-manifest: the cask declares no ${label} sha256 — regenerate the cask from the digest the checksum job computed`,
      );
    } else if (publishedSha === "" || publishedSha.toLowerCase() !== declaredSha.toLowerCase()) {
      problems.push(
        `cask-manifest: the cask declares sha256 ${declaredSha} which checksums.txt does not confirm for ${assetName} — regenerate the cask from the attached checksum manifest`,
      );
    }
  }

  for (const { label, url } of urls) {
    const segment = url === "" ? "" : urlTagSegment(url);
    if (segment === "") {
      problems.push(
        `cask-manifest: the ${label} address does not point into this release's download path — regenerate the cask from this tag's DMG assets`,
      );
    } else if (segment !== tag) {
      problems.push(
        `cask-manifest: the ${label} address points at release ${segment} but this release is ${tag} — regenerate the cask from this tag's DMG assets`,
      );
    }
  }
  return problems;
}
