import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("../package.json", import.meta.url);
const { version } = JSON.parse(readFileSync(root, "utf8"));
const out = new URL("../apps/web/src/version.ts", import.meta.url);
writeFileSync(
  out,
  `// generated by scripts/gen-version.mjs — single source: root package.json\nexport const APP_VERSION = ${JSON.stringify(version)};\n`,
);
console.log(`version.ts -> ${version}`);
