/**
 * P1-056: single version truth — the release tag stamps the tree, never the
 * other way around. The 0.2.0 ↔ v0.3.0 drift survived because bumping two
 * package.json files was a manual step; the preflight only DETECTED the drift.
 *
 * Usage:  npx tsx scripts/sync-version.ts <vX.Y.Z | X.Y.Z>
 * Stamps (relative to the repo root):
 *   package.json                → "version": "X.Y.Z"
 *   apps/desktop/package.json   → "version": "X.Y.Z"
 *   apps/web/src/version.ts     → APP_VERSION = "X.Y.Z"
 * Idempotent: re-running with the same version is a no-op. Then:
 *   git add -A && git commit -m "release: vX.Y.Z" && git tag vX.Y.Z && git push --follow-tags
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// fable #7: one validator, imported — never a divergent copy
import { SEMVER } from "./release-preflight";
export { SEMVER };

/** Pure core: takes file CONTENTS, returns the contents to write. No I/O. */
export function stampVersion(
  tag: string,
  current: { rootPkg: string; desktopPkg: string; webVersion: string },
): { files: Record<string, string>; version: string } {
  const bare = tag.startsWith("v") ? tag.slice(1) : tag;
  if (!SEMVER.test(bare)) throw new Error(`not a semver version: ${tag} — expected X.Y.Z`);
  const files: Record<string, string> = {};
  const root = JSON.parse(current.rootPkg) as { version?: string };
  const desk = JSON.parse(current.desktopPkg) as { version?: string };
  if (root.version !== bare) files["package.json"] = pkgWithVersion(current.rootPkg, bare);
  if (desk.version !== bare) files["apps/desktop/package.json"] = pkgWithVersion(current.desktopPkg, bare);
  if (current.webVersion !== bare)
    // fable #6: byte-identical to scripts/gen-version.mjs output — that script
    // runs on predev/prebuild and is the co-owner of this file.
    files["apps/web/src/version.ts"] = `// generated by scripts/gen-version.mjs — single source: root package.json\nexport const APP_VERSION = ${JSON.stringify(bare)};\n`;
  return { files, version: bare };
}

/** Replace only the top-level "version" field — every other key round-trips. */
export function pkgWithVersion(contents: string, bare: string): string {
  const pkg = JSON.parse(contents) as Record<string, unknown>;
  pkg.version = bare;
  return JSON.stringify(pkg, null, 2) + "\n";
}

function main(): void {
  const arg = process.argv[2];
  if (!arg) {
    console.error("usage: npx tsx scripts/sync-version.ts <vX.Y.Z | X.Y.Z>");
    process.exit(1);
  }
  const { files, version } = stampVersion(arg, {
    rootPkg: readFileSync("package.json", "utf8"),
    desktopPkg: readFileSync(join("apps", "desktop", "package.json"), "utf8"),
    webVersion: readFileSync(join("apps", "web", "src", "version.ts"), "utf8").match(/APP_VERSION = "([^"]+)"/)?.[1] ?? "",
  });
  const written: string[] = [];
  for (const [path, content] of Object.entries(files)) {
    writeFileSync(path, content);
    written.push(path);
  }
  if (!written.length) console.log(`already at ${version} — nothing to do`);
  else console.log(`stamped ${version} →\n  ${written.join("\n  ")}`);
  console.log(
    `\nnext:\n  git add -A && git commit -m "release: v${version}" && git tag v${version} && git push --follow-tags`,
  );
}

// tsx-safe entrypoint: compare real paths (macOS /private/tmp aliasing makes
// the naive `import.meta.url === file://argv[1]` check fail silently).
import { realpathSync } from "node:fs";
const invoked = (() => {
  try {
    return process.argv[1] ? realpathSync(process.argv[1]) : "";
  } catch {
    return "";
  }
})();
// import.meta.url is percent-encoded ("SSD%20Major") — fileURLToPath, always.
// fable #8: a probe failure (odd runner, --eval) must never break the import
// of this module from the test battery — fail to "not the entrypoint".
try {
  const here = realpathSync(fileURLToPath(import.meta.url));
  if (invoked && here === invoked) main();
} catch {}

